# Autogenerated! DO NOT EDIT!
# This justfile is autogenerated via https://std.divnix.com/reference/lib/cfg/just.html
# It can be used without Nix by running a locally installed  `just` binary.
# NOTE: Without Nix, you are responsible for having all task dependencies
# available locally!

# edit the key age with ragenix
age cell file:
    ragenix --edit ./nix/{{ cell }}/secretProfiles/{{ file }} --rules ./nix/{{ cell }}/secretProfiles/secrets.nix

# re-age key with ragenix
age-rekey cell:
    ragenix --rules ./nix/{{ cell }}/secretProfiles/secrets.nix --rekey

# Formats all changed source files
fmt:
    treefmt $(git diff --name-only --cached)

# nixos-generators with custom format
generate format-path name:
    nixos-generate --format-path ${PRJ_ROOT}/profiles/nixos-generators/{{ format-path }}.nix --system x86_64-linux --flake .#{{ name }}

# Colmena [action] [name] Machine
machine action name:
    colmena {{ action }} --on {{ name }}

# update sources with nvfetcher
nvfetcher path:
    nix develop github:GTrunSec/std-ext#update --refresh --command nvfetcher-update {{ path }}/sources.toml

# update default toolchain with nvfetcher
nvfetcher-default:
    nix develop github:GTrunSec/std-ext#update --refresh --command nvfetcher-update nix/vod/packages/_sources/sources.toml

# update emacs toolchain with nvfetcher
nvfetcher-emacs:
    nix develop github:GTrunSec/std-ext#update --refresh --command nvfetcher-update nix/vod/packages/_sources_emacs/sources.toml

# update packages via nvfetcher
nvfetcher-firefox-addons:
    nvfetcher-firefox-addons

# update packages via nvfetcher
nvfetcher-update cell:
    nix develop github:GTrunSec/std-ext#devShells.x86_64-linux.update --refresh --command nvfetcher-update nix/{{ cell }}/packages/sources.toml
