[acm-terminal]
src.git = "https://github.com/twlz0ne/acm-terminal"
fetch.github = "twlz0ne/acm-terminal"

[lsp-bridge]
src.git = "https://github.com/manateelazycat/lsp-bridge"
fetch.github = "manateelazycat/lsp-bridge"

### Chineese shit to remove
# [wen]
# src.git = "https://github.com/metaescape/Wen"
# fetch.github = "metaescape/Wen"

# [GodTian_Pinyin]
# src.git = "https://github.com/whatbeg/GodTian_Pinyin"
# fetch.github = "whatbeg/GodTian_Pinyin"
###

[jinx]
# Enchanted Spell Checker
src.git = "https://github.com/minad/jinx"
fetch.github = "minad/jinx"

### NOTE: vod
[chemacs]
src.git = "https://github.com/plexus/chemacs2"
fetch.git = "https://github.com/plexus/chemacs2"

[spacemacs]
src.git = "https://github.com/syl20bnr/spacemacs"
src.branch = "develop"
fetch.git = "https://github.com/syl20bnr/spacemacs"
git.leaveDotGit = true

[doom-emacs]
src.git = "https://github.com/hlissner/doom-emacs"
# src.branch = "develop"
fetch.git = "https://github.com/hlissner/doom-emacs"
git.leaveDotGit = true

[all-the-icons]
src.git =  "https://github.com/domtronn/all-the-icons.el"
fetch.git = "https://github.com/domtronn/all-the-icons.el"

[copilot-el]
src.git = "https://github.com/zerolfx/copilot.el.git"
fetch.git = "https://github.com/zerolfx/copilot.el.git"

[color-rg]
src.git = "https://github.com/manateelazycat/color-rg"
fetch.git = "https://github.com/manateelazycat/color-rg"

[org-pretty-table]
src.git = "https://github.com/Fuco1/org-pretty-table"
fetch.git = "https://github.com/Fuco1/org-pretty-table"

[org-protocol-capture-html]
src.git = "https://github.com/alphapapa/org-protocol-capture-html"
fetch.git = "https://github.com/alphapapa/org-protocol-capture-html"

[activity-watch-mode]
src.git = "https://github.com/pauldub/activity-watch-mode"
fetch.git = "https://github.com/pauldub/activity-watch-mode"

[nix-mode]
passthru = { ename = "nix-mode" }
src.git = "https://github.com/NixOS/nix-mode"
fetch.git = "https://github.com/NixOS/nix-mode"
