# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "415bf0a76e64a8a69028af06fc67b8bfa9e69b5c";
    src = fetchFromGitHub {
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "415bf0a76e64a8a69028af06fc67b8bfa9e69b5c";
      fetchSubmodules = false;
      sha256 = "sha256-0bDBaVoA7pqTCmTm07wTtEvE5AxgwLU/TX8BCt5H/LA=";
    };
    date = "2023-11-12";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "63eb19a10e4262c529f1b205ef61d69055350f49";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "63eb19a10e4262c529f1b205ef61d69055350f49";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x6CrLGslawBtixdXDyp1U3i5yY8tkuI75LkHvOyt6YI=";
    };
    date = "2023-07-31";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "be9d5dcda9c892e8ca1535e288620eec075eb0be";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sR0982CcdMXtn+hCRrvm3F2+60/JxQrGi3rEuioFEjI=";
    };
    date = "2023-09-09";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "65818c493f100a78bf55f5a0fe83f29521621b15";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "65818c493f100a78bf55f5a0fe83f29521621b15";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SW4KuLbGx54/WsFvwNtqG3Sm8HPFytc+9VUZ5+Geo8U=";
    };
    date = "2023-11-06";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "30a054f8569550853a9b6f947a2fe1ded7e7cc6b";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "30a054f8569550853a9b6f947a2fe1ded7e7cc6b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-uNtoduh/29dpBcE556G3qHdycdj0OGMridCTy3k5vX8=";
    };
    date = "2023-11-08";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "986398504d09e585c7d1a8d73a6394024fe6f164";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "986398504d09e585c7d1a8d73a6394024fe6f164";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-G9aHHbM+iX7LOG5eyyt7RmN6Do67eN65u1+kGHmcD6U=";
    };
    date = "2023-10-07";
  };
  jinx = {
    pname = "jinx";
    version = "25279e36701ad0bea1331ccfa009c07fda2f85d0";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "jinx";
      rev = "25279e36701ad0bea1331ccfa009c07fda2f85d0";
      fetchSubmodules = false;
      sha256 = "sha256-kSzD4ikh0eG9arymIss9WSf7laMcvAOPkUYsFqj9BXw=";
    };
    date = "2023-11-11";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "49053b9f0b4264a5e64a6e23bbe08d37c476e949";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "49053b9f0b4264a5e64a6e23bbe08d37c476e949";
      fetchSubmodules = false;
      sha256 = "sha256-h1RP8ZTBDZ4aiCcFfhK+mx8Uj9IFS++/zEKUS++xYok=";
    };
    date = "2023-11-12";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
  spacemacs = {
    pname = "spacemacs";
    version = "7313ef869eaf47e37670c35ce630738f1928bb05";
    src = fetchgit {
      url = "https://github.com/syl20bnr/spacemacs";
      rev = "7313ef869eaf47e37670c35ce630738f1928bb05";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-y/h6QqFZ+H65cnJNoFxczbhRmPjdfbNFKphk7C7Kp2M=";
    };
    date = "2023-11-12";
  };
}
