# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  acm-terminal = {
    pname = "acm-terminal";
    version = "321e05fc0398a6159925b858f46608ea07ef269e";
    src = fetchFromGitHub ({
      owner = "twlz0ne";
      repo = "acm-terminal";
      rev = "321e05fc0398a6159925b858f46608ea07ef269e";
      fetchSubmodules = false;
      sha256 = "sha256-Flw07EwH9z0E3tqXs4mStICJmoHfp60ALrP1GmUmeuU=";
    });
    date = "2023-02-15";
  };
  activity-watch-mode = {
    pname = "activity-watch-mode";
    version = "789ec3425623e43a29755e8daaa02305df8da8ed";
    src = fetchgit {
      url = "https://github.com/pauldub/activity-watch-mode";
      rev = "789ec3425623e43a29755e8daaa02305df8da8ed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-OoZSAiPX6mCiiETYWgl6H47AtQaLR0h8Q78fbr6kxU4=";
    };
    date = "2022-01-11";
  };
  all-the-icons = {
    pname = "all-the-icons";
    version = "8a7e70da843d99a36ad3c2b9e19924dcf533e5a0";
    src = fetchgit {
      url = "https://github.com/domtronn/all-the-icons.el";
      rev = "8a7e70da843d99a36ad3c2b9e19924dcf533e5a0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Cv1RCj1psugvO6rIaodE0ZDjNzpfz8XqDt0yaN7meB0=";
    };
    date = "2023-04-24";
  };
  chemacs = {
    pname = "chemacs";
    version = "c2d700b784c793cc82131ef86323801b8d6e67bb";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2";
      rev = "c2d700b784c793cc82131ef86323801b8d6e67bb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-/WtacZPr45lurS0hv+W8UGzsXY3RujkU5oGGGqjqG0Q=";
    };
    date = "2023-01-20";
  };
  color-rg = {
    pname = "color-rg";
    version = "a0f1e3623abded147551b3ecb74e94da59ecae13";
    src = fetchgit {
      url = "https://github.com/manateelazycat/color-rg";
      rev = "a0f1e3623abded147551b3ecb74e94da59ecae13";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-1UYJxscyMfdode3+AHcBuPK6Uw/ZikruaNUDdECbpzg=";
    };
    date = "2023-04-30";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "7cb7beda89145ccb86a4324860584545ec016552";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "7cb7beda89145ccb86a4324860584545ec016552";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-57ACMikRzHSwRkFdEn9tx87NlJsWDYEfmg2n2JH8Ig0=";
    };
    date = "2023-04-27";
  };
  doom-emacs = {
    pname = "doom-emacs";
    version = "042fe0c43831c8575abfdec4196ebd7305fa16ac";
    src = fetchgit {
      url = "https://github.com/hlissner/doom-emacs";
      rev = "042fe0c43831c8575abfdec4196ebd7305fa16ac";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-MJKJUp25+J/cpcUHvTK7wXy7GLwoAPDxaonwFETvtWQ=";
    };
    date = "2023-04-12";
  };
  jinx = {
    pname = "jinx";
    version = "187863e200bae23837b2509fa714f2e5ab8df2cf";
    src = fetchFromGitHub ({
      owner = "minad";
      repo = "jinx";
      rev = "187863e200bae23837b2509fa714f2e5ab8df2cf";
      fetchSubmodules = false;
      sha256 = "sha256-S4Da9m2uCXLAD/zjASO+tMo3Z9NglnQ4MTcPAc3w6oI=";
    });
    date = "2023-05-01";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "679d820bbcd180a51349862722b9086e061ea42d";
    src = fetchFromGitHub ({
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "679d820bbcd180a51349862722b9086e061ea42d";
      fetchSubmodules = false;
      sha256 = "sha256-pOS7Wd8j6ILch/2FZGPfGsOI3zidKFGeNxgs87VtGrs=";
    });
    date = "2023-05-02";
  };
  nix-mode = {
    pname = "nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchgit {
      url = "https://github.com/NixOS/nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    ename = "nix-mode";
    date = "2023-04-21";
  };
  org-pretty-table = {
    pname = "org-pretty-table";
    version = "38e4354bbf7a8d08294babd067fac697038119b1";
    src = fetchgit {
      url = "https://github.com/Fuco1/org-pretty-table";
      rev = "38e4354bbf7a8d08294babd067fac697038119b1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-IeHnoB9hpISwuzI+pKiU+5wvGvz9YJrG5amGg6DGgq4=";
    };
    date = "2023-03-19";
  };
  org-protocol-capture-html = {
    pname = "org-protocol-capture-html";
    version = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
    src = fetchgit {
      url = "https://github.com/alphapapa/org-protocol-capture-html";
      rev = "a912aaefae8abdada2b2479aec0ad53fcf0b57bf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+t8E+0Bxtl6YMU0SwA/vRD8kn1lSXd2PcBhIY001Xo=";
    };
    date = "2022-10-05";
  };
  spacemacs = {
    pname = "spacemacs";
    version = "c6c508254f4552549f70af5d131dc7882f0d35d3";
    src = fetchgit {
      url = "https://github.com/syl20bnr/spacemacs";
      rev = "c6c508254f4552549f70af5d131dc7882f0d35d3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-VpQiXxE5aeXsT0fT5fg4vGv7Kvb7xPopQtJNmZzTItc=";
    };
    date = "2023-04-29";
  };
}
