# nvfetcher.toml

[chatgpt-wrapper]
src.git = "https://github.com/mmabrouk/chatgpt-wrapper"
fetch.github = "mmabrouk/chatgpt-wrapper"

[langchain]
src.pypi = "langchain"
fetch.pypi = "langchain"

# [StevenBlack-hosts]
# src.git = "https://github.com/StevenBlack/hosts"
# fetch.github = "StevenBlack/hosts"

[brave]
src.github = "brave/brave-browser"
fetch.url = "https://github.com/brave/brave-browser/releases/download/v$ver/brave-browser_$ver_amd64.deb"
src.prefix = "v"

# [drawio]
# src.github = "jgraph/drawio-desktop"
# fetch.url = "https://github.com/jgraph/drawio-desktop/releases/download/v$ver/drawio-x86_64-$ver.rpm"
# src.prefix = "v"

# [chord]
# src.manual = "0.2.38"
# fetch.url = "https://github.com/PeterDing/chord/releases/download/v$ver/chord-$ver-linux-x86_64.AppImage"

# [wezterm-appimage]
# src.cmd = "date +%m-%d-%Y"
# fetch.url = "https://github.com/wez/wezterm/releases/download/nightly/WezTerm-nightly-Ubuntu18.04.AppImage"

# MAYBE:
# [motrix]
# src.github = "agalwood/Motrix"
# fetch.url = "https://github.com/agalwood/Motrix/releases/download/v$ver/Motrix-$ver.AppImage"
# src.prefix = "v"

[adguardhome]
src.github = "AdguardTeam/AdGuardHome"
fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/$ver/AdGuardHome_linux_amd64.tar.gz"

[spaceship-prompt]
src.git = "https://github.com/spaceship-prompt/spaceship-prompt"
fetch.github = "spaceship-prompt/spaceship-prompt"

### NOTE: promnesia :START:
[promnesia]
src.git = "https://github.com/karlicoss/promnesia"
fetch.github = "karlicoss/promnesia"

[HPI]
src.pypi = "HPI"
fetch.pypi = "HPI"

[hug]
src.pypi = "hug"
fetch.pypi = "hug"

[orgparse]
src.pypi = "orgparse"
fetch.pypi = "orgparse"

[open-in-editor]
src.git = "https://github.com/karlicoss/open-in-editor"
fetch.git = "https://github.com/karlicoss/open-in-editor"
### NOTE: promnesia :END:

[logseq]
src.github = "logseq/logseq"
# src.manual = "0.5.4"
fetch.url = "https://github.com/logseq/logseq/releases/download/$ver/logseq-linux-x64-$ver.AppImage"
###################

# Pkgs and overlays
#
[pam_u2f]
src.manual = "1.2.1"
fetch.url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-$ver.tar.gz"

[pam_usb]
src.git = "https://github.com/mcdope/pam_usb"
fetch.git = "https://github.com/mcdope/pam_usb"

[gpg-hd]
# src.git = "https://github.com/voobscout/gpg-hd"
# fetch.github = "voobscout/gpg-hd"
src.git = "https://github.com/Logicwax/gpg-hd"
fetch.github = "Logicwax/gpg-hd"

[trezor-agent]
src.manual = "v0.14.5"
fetch.github = "romanz/trezor-agent"
# NOTE: pypi has an older version!
# src.pypi = "trezor_agent"
# fetch.pypi = "trezor_agent"

[trezor-agent-subkeys]
src.git = "https://github.com/jrruethe/trezor-agent"
src.branch = "subkeys"
fetch.git = "https://github.com/jrruethe/trezor-agent"

[trezor-gpg-pinentry-tk]
src.pypi = "trezor-gpg-pinentry-tk"
fetch.pypi = "trezor-gpg-pinentry-tk"

[age-plugin-trezor]
src.git = "https://github.com/romanz/age-plugin-trezor"
fetch.github = "romanz/age-plugin-trezor"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[dbus-listen]
src.git = "https://github.com/voobscout/dbus-listen"
fetch.git = "https://github.com/voobscout/dbus-listen"

# [rofi-themes-extra]
# src.git = "https://github.com/davatorium/rofi-themes"
# fetch.git = "https://github.com/davatorium/rofi-themes"

# [nushell]
# src.github = "nushell/nushell"
# src.use_latest_release = true
# fetch.github = "nushell/nushell"
# cargo_lock = "Cargo.lock"
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[git-get]
src.git = "https://github.com/grdl/git-get"
fetch.github = "grdl/git-get"
passthru = { vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b" }

[shflags]
src.git = "https://github.com/kward/shflags"
fetch.github = "kward/shflags"

[shellspec]
src.git = "https://github.com/shellspec/shellspec"
fetch.github = "shellspec/shellspec"

[getoptions]
src.git = "https://github.com/ko1nksm/getoptions"
fetch.github = "ko1nksm/getoptions"

[rainbowsh]
src.git = "https://github.com/xr09/rainbow.sh"
fetch.github = "xr09/rainbow.sh"

[git-remote-ipfs]
src.git = "https://github.com/bqv/git-remote-ipfs"
fetch.github = "bqv/git-remote-ipfs"
passthru = { vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=" }

[git-pull-request-mirror]
src.git = "https://github.com/google/git-pull-request-mirror"
fetch.github = "google/git-pull-request-mirror"
passthru = { vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn" }

######
### kubernetes
######
# [k9s]
# src.github = "derailed/k9s"
# src.use_latest_release = true
# fetch.github = "derailed/k9s"

### cloud and friends
# [vultr-cli]
# src.github = "vultr/vultr-cli"
# src.use_latest_release = true
# fetch.github = "vultr/vultr-cli"

# [terraform]
# src.github = "hashicorp/terraform"
# src.use_latest_release = true
# fetch.github = "hashicorp/terraform"

#######
# [nyxt]
# #src.manual = "2.0.0"
# src.github = "atlas-engineer/nyxt"
# src.use_latest_release = true
# fetch.github = "atlas-engineer/nyxt"
# git.fetchSubmodules = true

#[cl-webkit2]
#src.git = "https://github.com/joachifm/cl-webkit"
#src.branch ="master"
#fetch.github = "joachifm/cl-webkit"

#[cl-qrencode]
#src.git = "https://github.com/jnjcc/cl-qrencode"
#src.branch ="master"
#fetch.github = "jnjcc/cl-qrencode"

########

[nix-index]
src.git = "https://github.com/bennofs/nix-index"
fetch.github = "bennofs/nix-index"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[nix-linter]
src.git = "https://github.com/Synthetica9/nix-linter"
fetch.git = "https://github.com/Synthetica9/nix-linter"

[lorri]
src.git = "https://github.com/nix-community/lorri"
src.branch = "canon"
fetch.github = "nix-community/lorri"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[console-solarized]
src.git = "https://github.com/adeverteuil/console-solarized"
fetch.github = "adeverteuil/console-solarized"

[brig]
src.git = "https://github.com/sahib/brig"
src.branch = "develop"
fetch.github = "sahib/brig"
passthru = { vendorSha256 = "sha256-pFrrMq7VFCwt8KRgJApCq8lPYv0P8hIUOxKJMN9QR0U=" }

[any-nix-shell]
src.git = "https://github.com/haslersn/any-nix-shell"
src.branch = "master"
fetch.github = "haslersn/any-nix-shell"

[nix-zsh-completions]
src.git = "https://github.com/spwhitt/nix-zsh-completions"
src.branch = "master"
fetch.github = "spwhitt/nix-zsh-completions"

# lisp overlays stuff
[stumpwm-git]
src.git = "https://github.com/stumpwm/stumpwm"
fetch.github = "stumpwm/stumpwm"
passthru = { system = "stumpwm", asd = "stumpwm" }

[quicklisp]
src.manual = "latest"
fetch.url = "https://beta.quicklisp.org/quicklisp.lisp"

# FIXME: broken nix builds after 189a730f73266999d5b8f992faf939c11d7815ad
[stumpwm]
src.manual = "189a730f73266999d5b8f992faf939c11d7815ad"
# src.git = "https://github.com/stumpwm/stumpwm"
fetch.github = "stumpwm/stumpwm"

[stumpwm-contrib]
src.git = "https://github.com/stumpwm/stumpwm-contrib"
fetch.github = "stumpwm/stumpwm-contrib"

[dbus]
src.git = "https://github.com/death/dbus"
fetch.git = "https://github.com/death/dbus"

[cl-hash-util]
src.git = "https://github.com/orthecreedence/cl-hash-util"
fetch.github = "orthecreedence/cl-hash-util"

[cl-strings]
src.git = "https://github.com/diogoalexandrefranco/cl-strings"
fetch.github = "diogoalexandrefranco/cl-strings"

[cl-shellwords]
src.git = "https://github.com/jorams/cl-shellwords"
fetch.github = "jorams/cl-shellwords"

[listopia]
src.git = "https://github.com/Dimercel/listopia"
fetch.github = "Dimercel/listopia"

[acl-compat]
src.git = "https://git.code.sf.net/p/portableaserve/git"
fetch.git = "https://git.code.sf.net/p/portableaserve/git"

[cl-syslog]
src.git = "https://github.com/lhope/cl-syslog"
fetch.github = "lhope/cl-syslog"

# hardware stuff
[rtl88x2bu]
src.git = "https://github.com/RinCat/RTL88x2BU-Linux-Driver"
fetch.github = "RinCat/RTL88x2BU-Linux-Driver"

[rtw89]
src.git = "https://github.com/lwfinger/rtw89"
fetch.github = "lwfinger/rtw89"

# hardware crypto stuff
[paper-store]
src.git = "https://github.com/nurupo/paper-store"
fetch.git = "https://github.com/nurupo/paper-store"

[pbkdf2-sha512]
src.git = "https://github.com/NixOS/nixpkgs"
fetch.url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c"

# [age-plugin-yubikey]
# src.git = "https://github.com/str4d/age-plugin-yubikey"
# fetch.git = "https://github.com/str4d/age-plugin-yubikey"
# cargo_locks = [ "Cargo.lock" ]
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

[rage]
src.git = "https://github.com/str4d/rage"
fetch.git = "https://github.com/str4d/rage"
cargo_lock = "Cargo.lock"
passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

# themes
# [sublimeSolarized]
# src.github = "braver/Solarized"
# fetch.github = "braver/Solarized"

# [numix-solarized-gtk-theme-bin]
# src.github = "Ferdi265/numix-solarized-gtk-theme"
# src.use_latest_release = true
# fetch.url = "https://github.com/Ferdi265/numix-solarized-gtk-theme/releases/download/20210831/NumixSolarized-20210831.tar.gz"

[numix-solarized-gtk-theme-git]
src.git = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git"
fetch.git = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git"

# Office apps
[masterpdfeditor]
# "5.8.70"
src.manual = "5.9.70"
fetch.url = "https://code-industry.net/public/master-pdf-editor-$ver-qt5.x86_64.tar.gz"

# zsh plugins
# "zdharma/fast-syntax-highlighting"
#
[zsh-plugin_aw-watcher-shell]
src.git = "https://github.com/voobscout/aw-watcher-shell"
fetch.git = "https://github.com/voobscout/aw-watcher-shell"

[zsh-plugin_zsh-history-substring-search]
src.git = "https://github.com/zsh-users/zsh-history-substring-search"
fetch.git = "https://github.com/zsh-users/zsh-history-substring-search"

[zsh-plugin_zsh-completions]
src.git = "https://github.com/zsh-users/zsh-completions"
fetch.git = "https://github.com/zsh-users/zsh-completions"

[zsh-plugin_clipboard]
src.git = "https://github.com/zpm-zsh/clipboard"
fetch.git = "https://github.com/zpm-zsh/clipboard"

[zsh-plugin_k]
src.git = "https://github.com/supercrabtree/k"
fetch.git = "https://github.com/supercrabtree/k"

[zsh-plugin_oh-my-zsh]
src.git = "https://github.com/robbyrussell/oh-my-zsh"
fetch.git = "https://github.com/robbyrussell/oh-my-zsh"

[zsh-plugin_zsh-syntax-highlighting]
src.git = "https://github.com/zsh-users/zsh-syntax-highlighting"
fetch.git = "https://github.com/zsh-users/zsh-syntax-highlighting"

[zsh-plugin_tipz]
src.git = "https://github.com/molovo/tipz"
fetch.git = "https://github.com/molovo/tipz"

[zsh-plugin_zsh-autopair]
src.git = "https://github.com/hlissner/zsh-autopair"
fetch.git = "https://github.com/hlissner/zsh-autopair"

[zsh-plugin_zsh-256color]
src.git = "https://github.com/chrissicool/zsh-256color"
fetch.git = "https://github.com/chrissicool/zsh-256color"

[zsh-plugin_zsh-autoenv]
src.git = "https://github.com/Tarrasch/zsh-autoenv"
fetch.git = "https://github.com/Tarrasch/zsh-autoenv"

### git and tools
[gitea-tea]
src.git = "https://gitea.com/gitea/tea"
fetch.git = "https://gitea.com/gitea/tea"

# [gitea-latest]
# src.github = "go-gitea/gitea"
# src.use_latest_release = true
# fetch.url = "https://github.com/go-gitea/gitea/releases/download/v1.18.3/gitea-src-1.18.3.tar.gz"
# fetch.github = "go-gitea/gitea"

# [gitea-legacy]
# # src.git = "https://github.com/go-gitea/gitea"
# src.manual = "1.13.1"
# # fetch.git = "https://github.com/go-gitea/gitea"
# fetch.url = "https://github.com/go-gitea/gitea/releases/download/v1.13.1/gitea-src-1.13.1.tar.gz"

# okteto-bin - k8s namespace for free
# [okteto]
# src.github = "okteto/okteto"
# src.use_latest_release = true
# fetch.github = "okteto/okteto"
# git.fetchSubmodules = true
# cannot pass on null value passthru = { vendorSha256 = "" }

#
[okteto-bin]
src.manual = "2.15.1"
fetch.url = "https://github.com/okteto/okteto/releases/download/$ver/okteto-Linux-x86_64"

#
[vgo2nix]
src.git = "https://github.com/nix-community/vgo2nix"
src.branch = "master"
fetch.git = "https://github.com/nix-community/vgo2nix"

### RUBYGEMS :START:
[rubygems-solargraph]
# src.github = "castwide/solargraph"
src.manual = "v0.44.2"
fetch.github = "castwide/solargraph"

# [rubygems-lita]
# src.github = "litaio/lita"
# src.use_latest_release = true
# fetch.github = "litaio/lita"

[rubygems-huginn]
src.manual = "68b759a3f0874507d1871cf5c4700950579818d9"
fetch.github = "huginn/huginn"

[rubygems-nodejs-16-10-0]
src.manual = "v16.10.0"
fetch.github = "nodejs/node"
### RUBYGEMS :END:

### openwrt
### https://github.com/stangri/source.openwrt.melmac.net/tree/master/nebula
[nebula-openwrt-armv7l]
src.manual = "1.6.1"
fetch.url = "https://github.com/slackhq/nebula/releases/download/v$ver/nebula-linux-arm-7.tar.gz"

### keyboard config agent
[uhk-agent]
# src.use_latest_release = true
# src.github = "UltimateHackingKeyboard/agent"
src.manual = "2.1.2"
fetch.url = "https://github.com/UltimateHackingKeyboard/agent/releases/download/v$ver/UHK.Agent-$ver-linux-x86_64.AppImage"

### TODO: Chuwi tablets
### https://github.com/onitake/gsl-firmware
### https://github.com/onitake/gslx680-acpi
### https://github.com/Red5d/Linux-on-Chuwi-HiBook-Pro/raw/master/silead_ts.fw
### https://github.com/lwfinger/rtl8723bs_bt

# PXE stuff
[ipxe]
src.git = "https://github.com/ipxe/ipxe"
fetch.git = "https://github.com/ipxe/ipxe"
# git.leaveDotGit = true

[kea-ma]
src.manual = "4.4.2"
fetch.url = "https://dl.cloudsmith.io/public/isc/keama/deb/ubuntu/pool/bionic/main/i/is/isc-dhcp-keama_4.4.2_amd64.deb"

[freedos]
src.manual = "1.3-rc5"
fetch.url = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc5/FD13-LiveCD.zip"

# [rescuezilla]
# src.use_latest_release = true
# src.github = "rescuezilla/rescuezilla"
# fetch.url = "https://github.com/rescuezilla/rescuezilla/releases/download/2.3.1/rescuezilla-2.3.1-64bit.impish.iso"

[zero-ui]
src.git = "https://github.com/dec0dOS/zero-ui"
fetch.git = "https://github.com/dec0dOS/zero-ui"

[ztncui]
src.git = "https://github.com/key-networks/ztncui"
fetch.git = "https://github.com/key-networks/ztncui"

# [zerotierone-github]
# src.use_latest_release = true
# src.github = "zerotier/ZeroTierOne"
# fetch.github = "zerotier/ZeroTierOne"

#
# [zeronsd]
# src.git = "https://github.com/voobscout/zeronsd"
# fetch.github = "voobscout/zeronsd"
# cargo_locks = ["Cargo.lock"]
# # FIXME: Makefile prevents proper function, find how to filterSource with nvfetcher
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

# [zeronsd]
# src.git = "https://github.com/zerotier/zeronsd"
# fetch.github = "zerotier/zeronsd"
# cargo_locks = ["Cargo.lock"]
# passthru = { cargoSha256 = "0000000000000000000000000000000000000000000000000000" }

# [k3s-github]
# src.use_latest_release = true
# src.github = "k3s-io/k3s"
# fetch.github = "k3s-io/k3s"

# [k3d-github]
# src.use_latest_release = true
# src.github = "k3d-io/k3d"
# fetch.github = "k3d-io/k3d"
# passthru = { vendorSha256 = null }

### ballerina
# [ballerina-lang]
# src.use_latest_release = true
# src.github = "ballerina-platform/ballerina-distribution"
# fetch.github = "ballerina-platform/ballerina-distribution"

### wso2
# [integration-studio]
# src.use_latest_release = true
# src.github = "wso2/integration-studio"
# fetch.github = "wso2/integration-studio"

# Crystal
# [crystal-lang]
# src.use_latest_release = true
# src.github = "crystal-lang/crystal"
# fetch.github = "crystal-lang/crystal"

# [crystal2nix]
# src.use_latest_release = true
# src.github = "nix-community/crystal2nix"
# fetch.github = "nix-community/crystal2nix"

# src.git = "https://github.com/nix-community/crystal2nix"
# fetch.git = "https://github.com/nix-community/crystal2nix"

[crystalline]
src.git = "https://github.com/elbywan/crystalline"
fetch.git = "https://github.com/elbywan/crystalline"

# [icr]
# src.use_latest_release = true
# src.github = "crystal-community/icr"
# fetch.github = "crystal-community/icr"

[xxhash2mac]
src.git = "https://github.com/njkli/xxhash2mac"
fetch.git = "https://github.com/njkli/xxhash2mac"

# [roadrunner]
# src.github = "roadrunner-server/roadrunner"
# fetch.github = "roadrunner-server/roadrunner"
# # passthru = { vendorSha256 = null }

[pass-secret-service]
src.git = "https://github.com/mdellweg/pass_secret_service.git"
fetch.git = "https://github.com/mdellweg/pass_secret_service.git"

### Remote access
# FIXME: [xorgxrdp]
# src.use_latest_release = true
# src.github = "neutrinolabs/xorgxrdp"
# fetch.github = "neutrinolabs/xorgxrdp"

[remmina]
src.manual = "v1.4.30"
fetch.git = "https://gitlab.com/Remmina/Remmina"

### adblocking
[StevenBlack-hosts]
src.git = "https://github.com/StevenBlack/hosts"
fetch.github = "StevenBlack/hosts"

# [adguardhome]
# src.github = "AdguardTeam/AdGuardHome"
# fetch.url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/$ver/AdGuardHome_linux_amd64.tar.gz"

[ledger-live-desktop]
# src.manual = "2.57.0"
src.manual = "2.60.0"
fetch.url = "https://download.live.ledger.com/ledger-live-desktop-$ver-linux-x86_64.AppImage"

# [ledger-live-desktop-systemd-patch]
# src.manual = "master"
# fetch.url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/applications/blockchains/ledger-live-desktop/systemd.patch"

# [activitywatch]
# src.github = "ActivityWatch/activitywatch"
# src.use_latest_release = true
# fetch.github = "ActivityWatch/activitywatch"
# git.fetchSubmodules = true
