# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.4.20231102";
    src = fetchurl {
      url = "https://pypi.org/packages/source/H/HPI/HPI-0.4.20231102.tar.gz";
      sha256 = "sha256-V3lzJs17I3zwaDowngD0gr1t0zRlMnuE7QZeb4dlbXA=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "3ec89cdd9e8835dfd85e7319651f9f1dc55546ac";
    src = fetchFromGitHub {
      owner = "StevenBlack";
      repo = "hosts";
      rev = "3ec89cdd9e8835dfd85e7319651f9f1dc55546ac";
      fetchSubmodules = false;
      sha256 = "sha256-ha3HPT/RxoUY5xHQGURrSSy5C5PlRzQws9fzZx3lAx4=";
    };
    date = "2023-11-14";
  };
  acl-compat = {
    pname = "acl-compat";
    version = "cac1d6920998ddcbee8310a873414732e707d8e5";
    src = fetchgit {
      url = "https://git.code.sf.net/p/portableaserve/git";
      rev = "cac1d6920998ddcbee8310a873414732e707d8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CvfiudyBNYQsyPFy05kjbhGVtwl56wKPAllqgi6uZio=";
    };
    date = "2019-07-20";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.41";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.41/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-nhcSAhA/9XvU3evCgMvHHrejP1sbojFw9GKz383Kk/U=";
    };
  };
  age-plugin-trezor = {
    pname = "age-plugin-trezor";
    version = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "age-plugin-trezor";
      rev = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
      fetchSubmodules = false;
      sha256 = "sha256-EXhbCjIl5xDfxOZIQEDWHSFnWabwlVC5EYWk4ezAXy8=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2021-01-01";
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
    src = fetchFromGitHub {
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "2537e5c6901ef934f8f44d61bcfe938b0fc9fa71";
      fetchSubmodules = false;
      sha256 = "sha256-j1DE0WTBGLmBLoPmqST9YVj9Jc4Mp8WXQILmPBzRlbM=";
    };
    date = "2023-11-08";
  };
  brave = {
    pname = "brave";
    version = "1.60.118";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.60.118/brave-browser_1.60.118_amd64.deb";
      sha256 = "sha256-Lo9F7z8gJJRId7LBfVTj18C65swDr8C7Mt1gNmXoSoY=";
    };
  };
  brig = {
    pname = "brig";
    version = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
    src = fetchFromGitHub {
      owner = "sahib";
      repo = "brig";
      rev = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
      fetchSubmodules = false;
      sha256 = "sha256-lCXSeTIZcIcVcblm9BTUMqTfxO7+BHYQNv6/RlPq14A=";
    };
    vendorSha256 = "sha256-pFrrMq7VFCwt8KRgJApCq8lPYv0P8hIUOxKJMN9QR0U=";
    date = "2021-03-23";
  };
  chatgpt-wrapper = {
    pname = "chatgpt-wrapper";
    version = "5a2b2ee7fc3edc8ddffcbac68c432cb7d0f963e1";
    src = fetchFromGitHub {
      owner = "mmabrouk";
      repo = "chatgpt-wrapper";
      rev = "5a2b2ee7fc3edc8ddffcbac68c432cb7d0f963e1";
      fetchSubmodules = false;
      sha256 = "sha256-L33GdOu2Y8SpFUvULB2xKx+oxbzARNlWQK51VcxFGc8=";
    };
    date = "2023-11-18";
  };
  cl-hash-util = {
    pname = "cl-hash-util";
    version = "43f6d363722bf849bef10010e07fca17f024fb9d";
    src = fetchFromGitHub {
      owner = "orthecreedence";
      repo = "cl-hash-util";
      rev = "43f6d363722bf849bef10010e07fca17f024fb9d";
      fetchSubmodules = false;
      sha256 = "sha256-A1pZT35RkA9xeQ7ulh2shrqEMUgSoYx8Ry3j1GyRWPU=";
    };
    date = "2023-07-05";
  };
  cl-shellwords = {
    pname = "cl-shellwords";
    version = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
    src = fetchFromGitHub {
      owner = "jorams";
      repo = "cl-shellwords";
      rev = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
      fetchSubmodules = false;
      sha256 = "sha256-9hKq54YOOEE3Vc/9LVUnqvcw/1G1rpcUVL+8GKJlqEY=";
    };
    date = "2015-09-20";
  };
  cl-strings = {
    pname = "cl-strings";
    version = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
    src = fetchFromGitHub {
      owner = "diogoalexandrefranco";
      repo = "cl-strings";
      rev = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
      fetchSubmodules = false;
      sha256 = "sha256-UpXjI9KsWvOhsjGSo1zVMNlD1I4Pwu9+cZoD60jREMk=";
    };
    date = "2021-03-08";
  };
  cl-syslog = {
    pname = "cl-syslog";
    version = "f62d524874616383650e30f7f23320005fd310c1";
    src = fetchFromGitHub {
      owner = "lhope";
      repo = "cl-syslog";
      rev = "f62d524874616383650e30f7f23320005fd310c1";
      fetchSubmodules = false;
      sha256 = "sha256-rH0zOgXR3BixtVaqcYPhIfZBjqYgWnqrORQfr1mBqFM=";
    };
    date = "2006-11-28";
  };
  console-solarized = {
    pname = "console-solarized";
    version = "26929b5e303703ec527b6f6e4569f351d9831e52";
    src = fetchFromGitHub {
      owner = "adeverteuil";
      repo = "console-solarized";
      rev = "26929b5e303703ec527b6f6e4569f351d9831e52";
      fetchSubmodules = false;
      sha256 = "sha256-QMxhuDuVHgw8+DpQAavtC3Dyg4rBmbrYoA8tKtamy3Y=";
    };
    date = "2018-10-28";
  };
  crystalline = {
    pname = "crystalline";
    version = "48f4b48658ba9268db8b2d56d402ce659d019e54";
    src = fetchgit {
      url = "https://github.com/elbywan/crystalline";
      rev = "48f4b48658ba9268db8b2d56d402ce659d019e54";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-EMRq8FqVhzdrlH/HPlJnE3DhjdEIsdxFV69jA1VvTpk=";
    };
    date = "2023-10-10";
  };
  dbus = {
    pname = "dbus";
    version = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
    src = fetchgit {
      url = "https://github.com/death/dbus";
      rev = "8bba6a0942232e9d7fa915b33bbe32dfedc5abb9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xbg3tPYfRNGJo+9F/58w2bDeZqV33Z871+ClSg4ACPk=";
    };
    date = "2023-11-04";
  };
  dbus-listen = {
    pname = "dbus-listen";
    version = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
    src = fetchgit {
      url = "https://github.com/voobscout/dbus-listen";
      rev = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WU3e7F0iNrxiS7WXzNbxnBp4oIru2pLihKbVIR236J4=";
    };
    date = "2022-09-09";
  };
  freedos = {
    pname = "freedos";
    version = "1.3-rc5";
    src = fetchurl {
      url = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc5/FD13-LiveCD.zip";
      sha256 = "sha256-SO3BVISYqb/1Mm0iFgR59qooD3rHhQBvP2LAyEVESXo=";
    };
  };
  getoptions = {
    pname = "getoptions";
    version = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
    src = fetchFromGitHub {
      owner = "ko1nksm";
      repo = "getoptions";
      rev = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
      fetchSubmodules = false;
      sha256 = "sha256-MJ4UUDmd+yykvRjgxx8MRZwlLNauDb8Bh8lS0QvkG+U=";
    };
    date = "2022-07-03";
  };
  git-get = {
    pname = "git-get";
    version = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
    src = fetchFromGitHub {
      owner = "grdl";
      repo = "git-get";
      rev = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
      fetchSubmodules = false;
      sha256 = "sha256-dBZNrhg4df7NDECq8B333dY/7OXEyPIByD7YHdV9moo=";
    };
    vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b";
    date = "2021-08-07";
  };
  git-pull-request-mirror = {
    pname = "git-pull-request-mirror";
    version = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
    src = fetchFromGitHub {
      owner = "google";
      repo = "git-pull-request-mirror";
      rev = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
      fetchSubmodules = false;
      sha256 = "sha256-OMtRSGRB1xRk3L3sIfEpagDQHNWNJBBOE5tuW7ic4Y4=";
    };
    vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn";
    date = "2020-05-13";
  };
  git-remote-ipfs = {
    pname = "git-remote-ipfs";
    version = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
    src = fetchFromGitHub {
      owner = "bqv";
      repo = "git-remote-ipfs";
      rev = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
      fetchSubmodules = false;
      sha256 = "sha256-59zv362KfuW1Lki9vfwe9fJfdm6o0+DTPDbI/L+Ugsk=";
    };
    vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=";
    date = "2021-01-24";
  };
  gitea-tea = {
    pname = "gitea-tea";
    version = "649b0b12726aaf9cec2b4ba3f5f6a1fdd2552d3c";
    src = fetchgit {
      url = "https://gitea.com/gitea/tea";
      rev = "649b0b12726aaf9cec2b4ba3f5f6a1fdd2552d3c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-91FPFlgeN/e2Srh5zbn1lMt1dgjtiyFAZ7hoVs28jXs=";
    };
    date = "2023-11-09";
  };
  gpg-hd = {
    pname = "gpg-hd";
    version = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
    src = fetchFromGitHub {
      owner = "Logicwax";
      repo = "gpg-hd";
      rev = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
      fetchSubmodules = false;
      sha256 = "sha256-O78meAbNTFh2ZhgxCbuA85kChtiR+fZ/S5jfvcQuymg=";
    };
    date = "2023-02-22";
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  ipxe = {
    pname = "ipxe";
    version = "77b07ea4fdc259d7253c6f9df2beda6e6c7a9d85";
    src = fetchgit {
      url = "https://github.com/ipxe/ipxe";
      rev = "77b07ea4fdc259d7253c6f9df2beda6e6c7a9d85";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oVN0cFEMqzMAKf6OUuE0SYrMnwt3otN1RfuzqF8x8E0=";
    };
    date = "2023-11-07";
  };
  kea-ma = {
    pname = "kea-ma";
    version = "4.4.2";
    src = fetchurl {
      url = "https://dl.cloudsmith.io/public/isc/keama/deb/ubuntu/pool/bionic/main/i/is/isc-dhcp-keama_4.4.2_amd64.deb";
      sha256 = "sha256-8PfGxIh5IhJfys5JlG3nTT1A8t+RP/rQBQ/SL9CojsA=";
    };
  };
  langchain = {
    pname = "langchain";
    version = "0.0.338";
    src = fetchurl {
      url = "https://pypi.org/packages/source/l/langchain/langchain-0.0.338.tar.gz";
      sha256 = "sha256-ySjM7KdwtcYrSAJN4WOqylygU5thPncmNp8mceKTToA=";
    };
  };
  ledger-live-desktop = {
    pname = "ledger-live-desktop";
    version = "2.60.0";
    src = fetchurl {
      url = "https://download.live.ledger.com/ledger-live-desktop-2.60.0-linux-x86_64.AppImage";
      sha256 = "sha256-dR6F6elUxZW3EuH71d5P9SOSDq5f5lAsYnrfWrsj2KA=";
    };
  };
  listopia = {
    pname = "listopia";
    version = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
    src = fetchFromGitHub {
      owner = "Dimercel";
      repo = "listopia";
      rev = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
      fetchSubmodules = false;
      sha256 = "sha256-IEoPmF0QC1S6xF/enlqy1rDX8qi/2bvacxWpCHaro0k=";
    };
    date = "2021-03-17";
  };
  logseq = {
    pname = "logseq";
    version = "0.9.20";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.9.20/logseq-linux-x64-0.9.20.AppImage";
      sha256 = "sha256-iT0Gc/ePx1tUNTPoE2Ol+dHUmbS4CkneZbyraRBx5Ak=";
    };
  };
  lorri = {
    pname = "lorri";
    version = "30bb920dec9f3ca0bd0bc6cd60b78ca2f90c69a9";
    src = fetchFromGitHub {
      owner = "nix-community";
      repo = "lorri";
      rev = "30bb920dec9f3ca0bd0bc6cd60b78ca2f90c69a9";
      fetchSubmodules = false;
      sha256 = "sha256-ciSQGuNOxDnsrlmByrXk0uPNKy4F+1lInq2e1hEq108=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-10-08";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub {
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    };
    date = "2021-04-20";
  };
  masterpdfeditor = {
    pname = "masterpdfeditor";
    version = "5.9.70";
    src = fetchurl {
      url = "https://code-industry.net/public/master-pdf-editor-5.9.70-qt5.x86_64.tar.gz";
      sha256 = "sha256-26Csx/Z9JF49+tvF4NweVClikMTZ25teFQX6hfbHcjw=";
    };
  };
  nebula-openwrt-armv7l = {
    pname = "nebula-openwrt-armv7l";
    version = "1.6.1";
    src = fetchurl {
      url = "https://github.com/slackhq/nebula/releases/download/v1.6.1/nebula-linux-arm-7.tar.gz";
      sha256 = "sha256-R5LXscl0myJ1bJwK8CYqN0HxTgiIGXlMzHs1/sDbi9M=";
    };
  };
  nix-index = {
    pname = "nix-index";
    version = "3dbd1454abba9bbc94035813d6367b376e0bfb24";
    src = fetchFromGitHub {
      owner = "bennofs";
      repo = "nix-index";
      rev = "3dbd1454abba9bbc94035813d6367b376e0bfb24";
      fetchSubmodules = false;
      sha256 = "sha256-optjx/MoJjpxql9cMLI+hEt6AwcpMOUc6ZCfqQ7KYbQ=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-08-24";
  };
  nix-linter = {
    pname = "nix-linter";
    version = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
    src = fetchgit {
      url = "https://github.com/Synthetica9/nix-linter";
      rev = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wWkRak3bQvE5dY/CXqNelK3XIoHOk48m3pQHWJWKpkI=";
    };
    date = "2021-07-20";
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "a7c8781b5a18026fbc3edb36397931526f243590";
    src = fetchFromGitHub {
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "a7c8781b5a18026fbc3edb36397931526f243590";
      fetchSubmodules = false;
      sha256 = "sha256-JStpIKU+jU6TkXToTONfdEhLjaASGzC+tRmSJRiqKWU=";
    };
    date = "2023-10-09";
  };
  numix-solarized-gtk-theme-git = {
    pname = "numix-solarized-gtk-theme-git";
    version = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
    src = fetchgit {
      url = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git";
      rev = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-r5xCe8Ew+/SuCUaZ0yjlumORTy/y1VwbQQjQ6uEyGsY=";
    };
    date = "2023-03-05";
  };
  okteto-bin = {
    pname = "okteto-bin";
    version = "2.15.1";
    src = fetchurl {
      url = "https://github.com/okteto/okteto/releases/download/2.15.1/okteto-Linux-x86_64";
      sha256 = "sha256-g6Bt7KfGTBiKHBX5ed1ci+6cd0Drqq8kLWKqquZEzII=";
    };
  };
  open-in-editor = {
    pname = "open-in-editor";
    version = "08057f04a8d025a44974cb83770851b0b9149f82";
    src = fetchgit {
      url = "https://github.com/karlicoss/open-in-editor";
      rev = "08057f04a8d025a44974cb83770851b0b9149f82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x7MqX6GLKsZahXAxbw6mVZ5gQP/Sar9EiHJgqhABW9s=";
    };
    date = "2021-02-28";
  };
  orgparse = {
    pname = "orgparse";
    version = "0.4.20231004";
    src = fetchurl {
      url = "https://pypi.org/packages/source/o/orgparse/orgparse-0.4.20231004.tar.gz";
      sha256 = "sha256-pOOK6tq/mYiw9npmrNCCedGCILy8QioSkGDCiQu6kaA=";
    };
  };
  pam_u2f = {
    pname = "pam_u2f";
    version = "1.2.1";
    src = fetchurl {
      url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.2.1.tar.gz";
      sha256 = "sha256-cOdBvKGXtktPvo3R9tV84ritWMp4Y1LFJfPy1EEliUw=";
    };
  };
  pam_usb = {
    pname = "pam_usb";
    version = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
    src = fetchgit {
      url = "https://github.com/mcdope/pam_usb";
      rev = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oSZ0+Cphy1+h6qn8IVKiv91+IhqUUOFnr+Ya+G+wPH0=";
    };
    date = "2023-03-21";
  };
  paper-store = {
    pname = "paper-store";
    version = "638a495e9b56262b981c7b19e82967495bdd1278";
    src = fetchgit {
      url = "https://github.com/nurupo/paper-store";
      rev = "638a495e9b56262b981c7b19e82967495bdd1278";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-aPxao4BZ15m6pEWPYhftbN/6Witu2GSydPforjt2sro=";
    };
    date = "2019-07-05";
  };
  pass-secret-service = {
    pname = "pass-secret-service";
    version = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
    src = fetchgit {
      url = "https://github.com/mdellweg/pass_secret_service.git";
      rev = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lrNU5bkG4/fMu5rDywfiI8vNHyBsMf/fiWIeEHug03c=";
    };
    date = "2022-07-18";
  };
  pbkdf2-sha512 = {
    pname = "pbkdf2-sha512";
    version = "498738589e1a3dab567c2d3abcc4b8c984a6f9c4";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c";
      sha256 = "sha256-OelyIsDDto6Ir22YY/UM+r9EBx6K8TNdjM3efzUJxE8=";
    };
    date = "2023-11-19";
  };
  promnesia = {
    pname = "promnesia";
    version = "ddbb65f601f3e2c5fc67483d54c5cd5744746033";
    src = fetchFromGitHub {
      owner = "karlicoss";
      repo = "promnesia";
      rev = "ddbb65f601f3e2c5fc67483d54c5cd5744746033";
      fetchSubmodules = false;
      sha256 = "sha256-ffJIzYcO6U70hSlXjsY7QGXyJpFkx8xdr0W8dLJFZek=";
    };
    date = "2023-11-17";
  };
  quicklisp = {
    pname = "quicklisp";
    version = "latest";
    src = fetchurl {
      url = "https://beta.quicklisp.org/quicklisp.lisp";
      sha256 = "sha256-SnpcKuvgcWQXBHhUJnOX4kpE0MzglhJ0EenOnM/rLBc=";
    };
  };
  rage = {
    pname = "rage";
    version = "488212d707155bd025bb9d220a7454cf30fdee3e";
    src = fetchgit {
      url = "https://github.com/str4d/rage";
      rev = "488212d707155bd025bb9d220a7454cf30fdee3e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-TimZ+ct6Xch5iT3Ci+gQ1oLUBGBTBW3xrnKXNkPisp0=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-08-07";
  };
  rainbowsh = {
    pname = "rainbowsh";
    version = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
    src = fetchFromGitHub {
      owner = "xr09";
      repo = "rainbow.sh";
      rev = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
      fetchSubmodules = false;
      sha256 = "sha256-F+Nabc/Fe5ET6lSkdll5YH/mEpKp3OlpaGk+u0rQpPQ=";
    };
    date = "2022-08-24";
  };
  remmina = {
    pname = "remmina";
    version = "v1.4.30";
    src = fetchgit {
      url = "https://gitlab.com/Remmina/Remmina";
      rev = "v1.4.30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gZxUvVxd72cegObEOvkLoiDdcJ1XO455RqSocBUQ4RA=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "980d7cc06e9fa51f0060972d4a1d947f8be4cb40";
    src = fetchFromGitHub {
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "980d7cc06e9fa51f0060972d4a1d947f8be4cb40";
      fetchSubmodules = false;
      sha256 = "sha256-8UbyrBkrW0Ma5SOdXDI3nHO+55KV9JT2kVoR8Ft4xtI=";
    };
    date = "2023-11-15";
  };
  rtw89 = {
    pname = "rtw89";
    version = "78a73b0ffa15111c3021fcc8c4b6d2605fc16d88";
    src = fetchFromGitHub {
      owner = "lwfinger";
      repo = "rtw89";
      rev = "78a73b0ffa15111c3021fcc8c4b6d2605fc16d88";
      fetchSubmodules = false;
      sha256 = "sha256-0Hzy2eO3Bj27DqplymjPNBcfYUrKbJLUo0kSlc2/Mes=";
    };
    date = "2023-11-09";
  };
  rubygems-huginn = {
    pname = "rubygems-huginn";
    version = "68b759a3f0874507d1871cf5c4700950579818d9";
    src = fetchFromGitHub {
      owner = "huginn";
      repo = "huginn";
      rev = "68b759a3f0874507d1871cf5c4700950579818d9";
      fetchSubmodules = false;
      sha256 = "sha256-VcsvrJeUVUgr6yo+x/+HvdwPqCKaqZLImJIE9BF2IxE=";
    };
  };
  rubygems-nodejs-16-10-0 = {
    pname = "rubygems-nodejs-16-10-0";
    version = "v16.10.0";
    src = fetchFromGitHub {
      owner = "nodejs";
      repo = "node";
      rev = "v16.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-YHhjHHJdRcKwok+EjIOHvtnr1OtZ44Ua1sdhnbV4OgI=";
    };
  };
  rubygems-solargraph = {
    pname = "rubygems-solargraph";
    version = "v0.44.2";
    src = fetchFromGitHub {
      owner = "castwide";
      repo = "solargraph";
      rev = "v0.44.2";
      fetchSubmodules = false;
      sha256 = "sha256-TTUXO4E4U7abctoe9ys6SUete77CfzGq4YJOegWgNkw=";
    };
  };
  shellspec = {
    pname = "shellspec";
    version = "f800240b606ed8d60f27ca687400836c0083e76a";
    src = fetchFromGitHub {
      owner = "shellspec";
      repo = "shellspec";
      rev = "f800240b606ed8d60f27ca687400836c0083e76a";
      fetchSubmodules = false;
      sha256 = "sha256-PyZBc7bmycV02nTpoDaA40m4DA1IuDmb/eCd3+RAp0o=";
    };
    date = "2022-05-04";
  };
  shflags = {
    pname = "shflags";
    version = "96694d58ce92065fdd8f8761d930765cb9a8d066";
    src = fetchFromGitHub {
      owner = "kward";
      repo = "shflags";
      rev = "96694d58ce92065fdd8f8761d930765cb9a8d066";
      fetchSubmodules = false;
      sha256 = "sha256-IJJEi8xmIco/IuN9LSf6qMacsG6jHQek9F0dPKEwviI=";
    };
    date = "2023-08-24";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "be826cbe2bb11a0675dd71f548ff1396608da7ea";
    src = fetchFromGitHub {
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "be826cbe2bb11a0675dd71f548ff1396608da7ea";
      fetchSubmodules = false;
      sha256 = "sha256-473Srq7aDe4R9UIVdQiG0P4vXNRPtg0r8Vgc+HIxZMQ=";
    };
    date = "2023-10-10";
  };
  stumpwm = {
    pname = "stumpwm";
    version = "189a730f73266999d5b8f992faf939c11d7815ad";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "189a730f73266999d5b8f992faf939c11d7815ad";
      fetchSubmodules = false;
      sha256 = "sha256-jPxMo3QfqfSYTkKYnCf6CQhkSJrX90p70amSXynBxnE=";
    };
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "54dfbeb553ad68272163c520655b6a4af4ad0430";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm-contrib";
      rev = "54dfbeb553ad68272163c520655b6a4af4ad0430";
      fetchSubmodules = false;
      sha256 = "sha256-kaI6B3TWSRBlVtzO4MZAJC08Xo6206J0MuTyKglaAqQ=";
    };
    date = "2023-10-26";
  };
  stumpwm-git = {
    pname = "stumpwm-git";
    version = "baf5df7467553c52ec925a3b44ab24186f08cd9b";
    src = fetchFromGitHub {
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "baf5df7467553c52ec925a3b44ab24186f08cd9b";
      fetchSubmodules = false;
      sha256 = "sha256-oRFF8s/3IpNuB4R1Tn5/Zn+MZBoM+hJ6CXXj+DWLk4Q=";
    };
    asd = "stumpwm";
    system = "stumpwm";
    date = "2023-10-13";
  };
  trezor-agent = {
    pname = "trezor-agent";
    version = "v0.14.5";
    src = fetchFromGitHub {
      owner = "romanz";
      repo = "trezor-agent";
      rev = "v0.14.5";
      fetchSubmodules = false;
      sha256 = "sha256-RISAy0efdatr9u4CWNRGnlffkC8ksw1NyRpJWKwqz+s=";
    };
  };
  trezor-agent-subkeys = {
    pname = "trezor-agent-subkeys";
    version = "eac2f8215f2c11a92faf30170277c57bb7289801";
    src = fetchgit {
      url = "https://github.com/jrruethe/trezor-agent";
      rev = "eac2f8215f2c11a92faf30170277c57bb7289801";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-DA5REsNQNykpbCFb6PJbgEBYiDh1kEq083wRZq+pIQM=";
    };
    date = "2023-06-09";
  };
  trezor-gpg-pinentry-tk = {
    pname = "trezor-gpg-pinentry-tk";
    version = "0.0.10";
    src = fetchurl {
      url = "https://pypi.org/packages/source/t/trezor-gpg-pinentry-tk/trezor-gpg-pinentry-tk-0.0.10.tar.gz";
      sha256 = "sha256-h/NJKbKBP5Sbq0BYJes1h2ka2/k2gSUr564qOQZeAc4=";
    };
  };
  uhk-agent = {
    pname = "uhk-agent";
    version = "2.1.2";
    src = fetchurl {
      url = "https://github.com/UltimateHackingKeyboard/agent/releases/download/v2.1.2/UHK.Agent-2.1.2-linux-x86_64.AppImage";
      sha256 = "sha256-G/UT1ec7rWl8xONZnT+dpHAFOQh6/s0Vq7MTqAcmJSA=";
    };
  };
  vgo2nix = {
    pname = "vgo2nix";
    version = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
    src = fetchgit {
      url = "https://github.com/nix-community/vgo2nix";
      rev = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6anZFfJe1Dw5LvwwR6e0EGtOrjwAQTHEdarbcMnTDEs=";
    };
    date = "2022-08-24";
  };
  xxhash2mac = {
    pname = "xxhash2mac";
    version = "f1013aba4892edd9b2467db764de20fa2b98c251";
    src = fetchgit {
      url = "https://github.com/njkli/xxhash2mac";
      rev = "f1013aba4892edd9b2467db764de20fa2b98c251";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lU7CbcP48POPKD8Pibn4qxFCIGkiAbY/fC6irXAO4TU=";
    };
    date = "2022-03-22";
  };
  zero-ui = {
    pname = "zero-ui";
    version = "6f7bc6c2c202e2b1b312b6ce75aeccdbe2f5ea41";
    src = fetchgit {
      url = "https://github.com/dec0dOS/zero-ui";
      rev = "6f7bc6c2c202e2b1b312b6ce75aeccdbe2f5ea41";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YPqnRYCSRIDnGWV5BhPwv35D0pXpbBEfgXocn+gGtVI=";
    };
    date = "2023-10-25";
  };
  zsh-plugin_aw-watcher-shell = {
    pname = "zsh-plugin_aw-watcher-shell";
    version = "7dd9771d5c202b671d1ba111af520a30917639f9";
    src = fetchgit {
      url = "https://github.com/voobscout/aw-watcher-shell";
      rev = "7dd9771d5c202b671d1ba111af520a30917639f9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xDgr/e2wuFsMl6vJsvszgrKuEOO97dds9un3BWvqQIw=";
    };
    date = "2023-11-19";
  };
  zsh-plugin_clipboard = {
    pname = "zsh-plugin_clipboard";
    version = "354a4e493da5736d19d14e7769d98f357eff7323";
    src = fetchgit {
      url = "https://github.com/zpm-zsh/clipboard";
      rev = "354a4e493da5736d19d14e7769d98f357eff7323";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GDWxib4k2vwfSZ/R5fyXRx6piOYPzJ1hyzCNOg7QqxU=";
    };
    date = "2023-11-05";
  };
  zsh-plugin_k = {
    pname = "zsh-plugin_k";
    version = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
    src = fetchgit {
      url = "https://github.com/supercrabtree/k";
      rev = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-32rJjBzqS2e6w/L78KMNwQRg4E3sqqdAmb87XEhqbRQ=";
    };
    date = "2018-09-09";
  };
  zsh-plugin_oh-my-zsh = {
    pname = "zsh-plugin_oh-my-zsh";
    version = "c8e600f39779c6d2ef75b40304b5391a541c41df";
    src = fetchgit {
      url = "https://github.com/robbyrussell/oh-my-zsh";
      rev = "c8e600f39779c6d2ef75b40304b5391a541c41df";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-D6P8jferap3yqQvs2zpQHvbgGf0jxOlBPieOwyts3Qs=";
    };
    date = "2023-11-15";
  };
  zsh-plugin_tipz = {
    pname = "zsh-plugin_tipz";
    version = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
    src = fetchgit {
      url = "https://github.com/molovo/tipz";
      rev = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oFZJwHYDfK4f53lhcZg6PCw2AgHxFC0CRiqiinKZz8k=";
    };
    date = "2018-05-03";
  };
  zsh-plugin_zsh-256color = {
    pname = "zsh-plugin_zsh-256color";
    version = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
    src = fetchgit {
      url = "https://github.com/chrissicool/zsh-256color";
      rev = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-P/pbpDJmsMSZkNi5GjVTDy7R+OxaIVZhb/bEnYQlaLo=";
    };
    date = "2022-09-13";
  };
  zsh-plugin_zsh-autoenv = {
    pname = "zsh-plugin_zsh-autoenv";
    version = "e9809c1bd28496e025ca05576f574e08e93e12e8";
    src = fetchgit {
      url = "https://github.com/Tarrasch/zsh-autoenv";
      rev = "e9809c1bd28496e025ca05576f574e08e93e12e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SxDRldr9eqRtPQ3IWFKX0Q+vEG8Ry34PNRZ/I16aju0=";
    };
    date = "2018-09-14";
  };
  zsh-plugin_zsh-autopair = {
    pname = "zsh-plugin_zsh-autopair";
    version = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
    src = fetchgit {
      url = "https://github.com/hlissner/zsh-autopair";
      rev = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PXHxPxFeoYXYMOC29YQKDdMnqTO0toyA7eJTSCV6PGE=";
    };
    date = "2022-10-03";
  };
  zsh-plugin_zsh-completions = {
    pname = "zsh-plugin_zsh-completions";
    version = "634736c009a8c982b798b2edee93a0dfc6ef1a54";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-completions";
      rev = "634736c009a8c982b798b2edee93a0dfc6ef1a54";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-+X7RzRcId5+GDhWhx432OyiyJQHJMsdkwybTVOctUT8=";
    };
    date = "2023-11-16";
  };
  zsh-plugin_zsh-history-substring-search = {
    pname = "zsh-plugin_zsh-history-substring-search";
    version = "19b887667a155befeb5850f0af46a45cc5311ae2";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-history-substring-search";
      rev = "19b887667a155befeb5850f0af46a45cc5311ae2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-uv7yThQQN8LRqmEebhVblJ1VlClAd698xkYGpsZSkKc=";
    };
    date = "2023-11-08";
  };
  zsh-plugin_zsh-syntax-highlighting = {
    pname = "zsh-plugin_zsh-syntax-highlighting";
    version = "bb27265aeeb0a22fb77f1275118a5edba260ec47";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-syntax-highlighting";
      rev = "bb27265aeeb0a22fb77f1275118a5edba260ec47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-psIOBZnrANu1Gzce5oc0T1IO2vuIhHIFTyl/wJUGsm0=";
    };
    date = "2023-10-29";
  };
  ztncui = {
    pname = "ztncui";
    version = "1b2284864de48d2dcae22582fff122fe24909c3d";
    src = fetchgit {
      url = "https://github.com/key-networks/ztncui";
      rev = "1b2284864de48d2dcae22582fff122fe24909c3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-V4W2l1/rkk/Q+UuPMSj51Z7H6zQMPpJ5NUfv6WQ2XXQ=";
    };
    date = "2023-08-31";
  };
}
