# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  HPI = {
    pname = "HPI";
    version = "0.3.20230327";
    src = fetchurl {
      url = "https://pypi.io/packages/source/H/HPI/HPI-0.3.20230327.tar.gz";
      sha256 = "sha256-0QkuK8hzJL/KzZmgNSjZ+Ts6lJcmYNmSsj8cofG5/Wk=";
    };
  };
  StevenBlack-hosts = {
    pname = "StevenBlack-hosts";
    version = "de91e825b0d7a3a2e614e6b46a5895595544505a";
    src = fetchFromGitHub ({
      owner = "StevenBlack";
      repo = "hosts";
      rev = "de91e825b0d7a3a2e614e6b46a5895595544505a";
      fetchSubmodules = false;
      sha256 = "sha256-a4gn7rtIp6Rm+TDKvYUraHP+IjE3ftMvlsER25TjCUM=";
    });
    date = "2023-04-30";
  };
  acl-compat = {
    pname = "acl-compat";
    version = "cac1d6920998ddcbee8310a873414732e707d8e5";
    src = fetchgit {
      url = "https://git.code.sf.net/p/portableaserve/git";
      rev = "cac1d6920998ddcbee8310a873414732e707d8e5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-CvfiudyBNYQsyPFy05kjbhGVtwl56wKPAllqgi6uZio=";
    };
    date = "2019-07-20";
  };
  adguardhome = {
    pname = "adguardhome";
    version = "v0.107.29";
    src = fetchurl {
      url = "https://github.com/AdguardTeam/AdGuardHome/releases/download/v0.107.29/AdGuardHome_linux_amd64.tar.gz";
      sha256 = "sha256-M4VfjRnrqYxKc9neIJndJoa8D44RRIjN5ItE4Ec6VKY=";
    };
  };
  age-plugin-trezor = {
    pname = "age-plugin-trezor";
    version = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
    src = fetchFromGitHub ({
      owner = "romanz";
      repo = "age-plugin-trezor";
      rev = "1a89e1aec4aa6ee85987883146c5decd42a47a39";
      fetchSubmodules = false;
      sha256 = "sha256-EXhbCjIl5xDfxOZIQEDWHSFnWabwlVC5EYWk4ezAXy8=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2021-01-01";
  };
  any-nix-shell = {
    pname = "any-nix-shell";
    version = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
    src = fetchFromGitHub ({
      owner = "haslersn";
      repo = "any-nix-shell";
      rev = "c8536fa43f0e8b506e9dd1a91e2f01ceccca0251";
      fetchSubmodules = false;
      sha256 = "sha256-dQd1/RYH/j3R7MgMoz3EZ2Nxf3XXYCTKxBvi+cvyV2g=";
    });
    date = "2022-12-11";
  };
  brave = {
    pname = "brave";
    version = "1.50.121";
    src = fetchurl {
      url = "https://github.com/brave/brave-browser/releases/download/v1.50.121/brave-browser_1.50.121_amd64.deb";
      sha256 = "sha256-sV7cENBCQLs8VpJT11B71IjuGOlexd5m/Wlv/9vqtWE=";
    };
  };
  brig = {
    pname = "brig";
    version = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
    src = fetchFromGitHub ({
      owner = "sahib";
      repo = "brig";
      rev = "6b7eccf8fcbd907fc759f8ca8aa814df8499e2ed";
      fetchSubmodules = false;
      sha256 = "sha256-lCXSeTIZcIcVcblm9BTUMqTfxO7+BHYQNv6/RlPq14A=";
    });
    vendorSha256 = "sha256-pFrrMq7VFCwt8KRgJApCq8lPYv0P8hIUOxKJMN9QR0U=";
    date = "2021-03-23";
  };
  chatgpt-wrapper = {
    pname = "chatgpt-wrapper";
    version = "44755fff95f939d06ad4961d0b1409bdca114729";
    src = fetchFromGitHub ({
      owner = "mmabrouk";
      repo = "chatgpt-wrapper";
      rev = "44755fff95f939d06ad4961d0b1409bdca114729";
      fetchSubmodules = false;
      sha256 = "sha256-Zf1BqQoHcPchv67TiJbbLJ5k2Cf4WAhVGkQXVDYa4yM=";
    });
    date = "2023-04-23";
  };
  cl-hash-util = {
    pname = "cl-hash-util";
    version = "91d17d3e9208db9438b72bb60037644fd79fb497";
    src = fetchFromGitHub ({
      owner = "orthecreedence";
      repo = "cl-hash-util";
      rev = "91d17d3e9208db9438b72bb60037644fd79fb497";
      fetchSubmodules = false;
      sha256 = "sha256-6iDMXSS3OLHqDayYpCMboPKSxXzoEYxZETygVgABzTY=";
    });
    date = "2019-01-05";
  };
  cl-shellwords = {
    pname = "cl-shellwords";
    version = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
    src = fetchFromGitHub ({
      owner = "jorams";
      repo = "cl-shellwords";
      rev = "313576b9f6b925cbbc3dcf5e49e8f47c9c1b46bc";
      fetchSubmodules = false;
      sha256 = "sha256-9hKq54YOOEE3Vc/9LVUnqvcw/1G1rpcUVL+8GKJlqEY=";
    });
    date = "2015-09-20";
  };
  cl-strings = {
    pname = "cl-strings";
    version = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
    src = fetchFromGitHub ({
      owner = "diogoalexandrefranco";
      repo = "cl-strings";
      rev = "93ec4177fc51f403a9f1ef0a8933f36d917f2140";
      fetchSubmodules = false;
      sha256 = "sha256-UpXjI9KsWvOhsjGSo1zVMNlD1I4Pwu9+cZoD60jREMk=";
    });
    date = "2021-03-08";
  };
  cl-syslog = {
    pname = "cl-syslog";
    version = "f62d524874616383650e30f7f23320005fd310c1";
    src = fetchFromGitHub ({
      owner = "lhope";
      repo = "cl-syslog";
      rev = "f62d524874616383650e30f7f23320005fd310c1";
      fetchSubmodules = false;
      sha256 = "sha256-rH0zOgXR3BixtVaqcYPhIfZBjqYgWnqrORQfr1mBqFM=";
    });
    date = "2006-11-28";
  };
  console-solarized = {
    pname = "console-solarized";
    version = "26929b5e303703ec527b6f6e4569f351d9831e52";
    src = fetchFromGitHub ({
      owner = "adeverteuil";
      repo = "console-solarized";
      rev = "26929b5e303703ec527b6f6e4569f351d9831e52";
      fetchSubmodules = false;
      sha256 = "sha256-QMxhuDuVHgw8+DpQAavtC3Dyg4rBmbrYoA8tKtamy3Y=";
    });
    date = "2018-10-28";
  };
  crystalline = {
    pname = "crystalline";
    version = "ff6a712947a9f1aa1eed90478d5d23942585c4be";
    src = fetchgit {
      url = "https://github.com/elbywan/crystalline";
      rev = "ff6a712947a9f1aa1eed90478d5d23942585c4be";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-zm8me/Xsx3t08mFvJdt0FmIsOpkV5bz3KYrloYq3KXE=";
    };
    date = "2023-04-18";
  };
  dbus = {
    pname = "dbus";
    version = "f4d1a99cfb38ded33f4fb58bb5522815f530b3c3";
    src = fetchgit {
      url = "https://github.com/death/dbus";
      rev = "f4d1a99cfb38ded33f4fb58bb5522815f530b3c3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SnjJfvQtsWMgHl8EZFhhv8NtMXRi8lCXiN7kg0kghb8=";
    };
    date = "2020-06-03";
  };
  dbus-listen = {
    pname = "dbus-listen";
    version = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
    src = fetchgit {
      url = "https://github.com/voobscout/dbus-listen";
      rev = "e7aeedfbcdc18e3ea2d45cf6931e38d350096f2f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WU3e7F0iNrxiS7WXzNbxnBp4oIru2pLihKbVIR236J4=";
    };
    date = "2022-09-09";
  };
  freedos = {
    pname = "freedos";
    version = "1.3-rc5";
    src = fetchurl {
      url = "https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc5/FD13-LiveCD.zip";
      sha256 = "sha256-SO3BVISYqb/1Mm0iFgR59qooD3rHhQBvP2LAyEVESXo=";
    };
  };
  getoptions = {
    pname = "getoptions";
    version = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
    src = fetchFromGitHub ({
      owner = "ko1nksm";
      repo = "getoptions";
      rev = "a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa";
      fetchSubmodules = false;
      sha256 = "sha256-MJ4UUDmd+yykvRjgxx8MRZwlLNauDb8Bh8lS0QvkG+U=";
    });
    date = "2022-07-03";
  };
  git-get = {
    pname = "git-get";
    version = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
    src = fetchFromGitHub ({
      owner = "grdl";
      repo = "git-get";
      rev = "8cd27a8f629317bd27432f2e9a4bd00561b3b21e";
      fetchSubmodules = false;
      sha256 = "sha256-dBZNrhg4df7NDECq8B333dY/7OXEyPIByD7YHdV9moo=";
    });
    vendorSha256 = "05k6w4knk7fdjm9qm272nlrk47rzjr18g0fp4j57f5ncq26cxr8b";
    date = "2021-08-07";
  };
  git-pull-request-mirror = {
    pname = "git-pull-request-mirror";
    version = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
    src = fetchFromGitHub ({
      owner = "google";
      repo = "git-pull-request-mirror";
      rev = "3d342363b0e1f2da4e59ac01baf4601bcf233bf9";
      fetchSubmodules = false;
      sha256 = "sha256-OMtRSGRB1xRk3L3sIfEpagDQHNWNJBBOE5tuW7ic4Y4=";
    });
    vendorSha256 = "0789v1r6my256pncs0105yji28ifchj6ppfiy8gavglgclq3cgvn";
    date = "2020-05-13";
  };
  git-remote-ipfs = {
    pname = "git-remote-ipfs";
    version = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
    src = fetchFromGitHub ({
      owner = "bqv";
      repo = "git-remote-ipfs";
      rev = "12b3f421c19eb5548ae76b8c79c9581a428329e0";
      fetchSubmodules = false;
      sha256 = "sha256-59zv362KfuW1Lki9vfwe9fJfdm6o0+DTPDbI/L+Ugsk=";
    });
    vendorSha256 = "hkenInaS6PFnu/Z0oz32Y4B4BmM5+l5AB2/K1f/LxqA=";
    date = "2021-01-24";
  };
  gitea-tea = {
    pname = "gitea-tea";
    version = "7040c350ae5ed8542dbd2b336f6605158bb91bad";
    src = fetchgit {
      url = "https://gitea.com/gitea/tea";
      rev = "7040c350ae5ed8542dbd2b336f6605158bb91bad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-R1xloJRFhSvrWm+EvQH/aF9c/RBpQ4ezkYfkwbf2A7s=";
    };
    date = "2023-05-01";
  };
  gpg-hd = {
    pname = "gpg-hd";
    version = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
    src = fetchFromGitHub ({
      owner = "Logicwax";
      repo = "gpg-hd";
      rev = "ab5366a380dde2182f28e4e9b97d9a92347a258c";
      fetchSubmodules = false;
      sha256 = "sha256-O78meAbNTFh2ZhgxCbuA85kChtiR+fZ/S5jfvcQuymg=";
    });
    date = "2023-02-22";
  };
  hug = {
    pname = "hug";
    version = "2.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/h/hug/hug-2.6.1.tar.gz";
      sha256 = "sha256-sO2s4qy2GIc3ecnObs+RZdtU/vlcIiYvVwD83Z/rrsk=";
    };
  };
  ipxe = {
    pname = "ipxe";
    version = "bd13697446e758d5fed6afcba8f3e9883b2e2de7";
    src = fetchgit {
      url = "https://github.com/ipxe/ipxe";
      rev = "bd13697446e758d5fed6afcba8f3e9883b2e2de7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0Np9+AvAHCnnJWKbUCvddCclWpKqoUU1SlkdjFTMPCA=";
    };
    date = "2023-04-10";
  };
  kea-ma = {
    pname = "kea-ma";
    version = "4.4.2";
    src = fetchurl {
      url = "https://dl.cloudsmith.io/public/isc/keama/deb/ubuntu/pool/bionic/main/i/is/isc-dhcp-keama_4.4.2_amd64.deb";
      sha256 = "sha256-8PfGxIh5IhJfys5JlG3nTT1A8t+RP/rQBQ/SL9CojsA=";
    };
  };
  langchain = {
    pname = "langchain";
    version = "0.0.154";
    src = fetchurl {
      url = "https://pypi.io/packages/source/l/langchain/langchain-0.0.154.tar.gz";
      sha256 = "sha256-oXuCneejE0VJxBufXB0dGshnN1lUJGHchOhJPrJMGdc=";
    };
  };
  ledger-live-desktop = {
    pname = "ledger-live-desktop";
    version = "2.57.0";
    src = fetchurl {
      url = "https://download.live.ledger.com/ledger-live-desktop-2.57.0-linux-x86_64.AppImage";
      sha256 = "sha256-fXvCj9eBEp/kGPSiNUdir19eU0x461KzXgl5YgeapHI=";
    };
  };
  listopia = {
    pname = "listopia";
    version = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
    src = fetchFromGitHub ({
      owner = "Dimercel";
      repo = "listopia";
      rev = "2d2a1a3c35580252ca0085e15ebf625f73230d60";
      fetchSubmodules = false;
      sha256 = "sha256-IEoPmF0QC1S6xF/enlqy1rDX8qi/2bvacxWpCHaro0k=";
    });
    date = "2021-03-17";
  };
  logseq = {
    pname = "logseq";
    version = "0.9.4";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/0.9.4/logseq-linux-x64-0.9.4.AppImage";
      sha256 = "sha256-K04iIa/WnRtcHwRUHJbKqXO9c4l5xwHPvnwN5WX/Row=";
    };
  };
  lorri = {
    pname = "lorri";
    version = "803fadb70907dca3afd93176aa9bc771be80d471";
    src = fetchFromGitHub ({
      owner = "nix-community";
      repo = "lorri";
      rev = "803fadb70907dca3afd93176aa9bc771be80d471";
      fetchSubmodules = false;
      sha256 = "sha256-eR8i7pSUW/I7wCR+vMZLC046paBqxOsP7E8L/AlORtw=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2022-12-30";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  masterpdfeditor = {
    pname = "masterpdfeditor";
    version = "5.9.06";
    src = fetchurl {
      url = "https://code-industry.net/public/master-pdf-editor-5.9.06-qt5.x86_64.tar.gz";
      sha256 = "sha256-F9MeZhCMGE/z7v70lC/Bt1vPEuRMyrGBLT/gMH2gm3I=";
    };
  };
  nebula-openwrt-armv7l = {
    pname = "nebula-openwrt-armv7l";
    version = "1.6.1";
    src = fetchurl {
      url = "https://github.com/slackhq/nebula/releases/download/v1.6.1/nebula-linux-arm-7.tar.gz";
      sha256 = "sha256-R5LXscl0myJ1bJwK8CYqN0HxTgiIGXlMzHs1/sDbi9M=";
    };
  };
  nix-index = {
    pname = "nix-index";
    version = "a8ceb75b5f447ef5d0d5569dfd19401624b6c604";
    src = fetchFromGitHub ({
      owner = "bennofs";
      repo = "nix-index";
      rev = "a8ceb75b5f447ef5d0d5569dfd19401624b6c604";
      fetchSubmodules = false;
      sha256 = "sha256-3CjyXgX2Jfh4414f0qkWXYAj93Jidz076P6j6wH6VvI=";
    });
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-02-13";
  };
  nix-linter = {
    pname = "nix-linter";
    version = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
    src = fetchgit {
      url = "https://github.com/Synthetica9/nix-linter";
      rev = "ecdd50750fd3ffaff83c0637474b884a0c38f8b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-wWkRak3bQvE5dY/CXqNelK3XIoHOk48m3pQHWJWKpkI=";
    };
    date = "2021-07-20";
  };
  nix-zsh-completions = {
    pname = "nix-zsh-completions";
    version = "6a1bfc024481bdba568f2ced65e02f3a359a7692";
    src = fetchFromGitHub ({
      owner = "spwhitt";
      repo = "nix-zsh-completions";
      rev = "6a1bfc024481bdba568f2ced65e02f3a359a7692";
      fetchSubmodules = false;
      sha256 = "sha256-aXetjkl5nPuYHHyuX59ywXF+4Xg+PUCV6Y2u+g18gEk=";
    });
    date = "2023-01-29";
  };
  numix-solarized-gtk-theme-git = {
    pname = "numix-solarized-gtk-theme-git";
    version = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
    src = fetchgit {
      url = "https://github.com/Ferdi265/numix-solarized-gtk-theme.git";
      rev = "2c5a85bd79c7b7d509ec14dd00d310cfe9f9afd2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-r5xCe8Ew+/SuCUaZ0yjlumORTy/y1VwbQQjQ6uEyGsY=";
    };
    date = "2023-03-05";
  };
  okteto-bin = {
    pname = "okteto-bin";
    version = "2.11.1";
    src = fetchurl {
      url = "https://github.com/okteto/okteto/releases/download/2.11.1/okteto-Linux-x86_64";
      sha256 = "sha256-+HKE6Dyych90O3dNMCO5az3UOJzLflhWCB7wBw98Y3o=";
    };
  };
  open-in-editor = {
    pname = "open-in-editor";
    version = "08057f04a8d025a44974cb83770851b0b9149f82";
    src = fetchgit {
      url = "https://github.com/karlicoss/open-in-editor";
      rev = "08057f04a8d025a44974cb83770851b0b9149f82";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x7MqX6GLKsZahXAxbw6mVZ5gQP/Sar9EiHJgqhABW9s=";
    };
    date = "2021-02-28";
  };
  orgparse = {
    pname = "orgparse";
    version = "0.3.2";
    src = fetchurl {
      url = "https://pypi.io/packages/source/o/orgparse/orgparse-0.3.2.tar.gz";
      sha256 = "sha256-RRBQ55rLelHGXcmbkJXq5NUL1ZhUE1T552PLTL31mlU=";
    };
  };
  pam_u2f = {
    pname = "pam_u2f";
    version = "1.2.1";
    src = fetchurl {
      url = "https://developers.yubico.com/pam-u2f/Releases/pam_u2f-1.2.1.tar.gz";
      sha256 = "sha256-cOdBvKGXtktPvo3R9tV84ritWMp4Y1LFJfPy1EEliUw=";
    };
  };
  pam_usb = {
    pname = "pam_usb";
    version = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
    src = fetchgit {
      url = "https://github.com/mcdope/pam_usb";
      rev = "2eeaaff4caf5c85dd1f4858f5f2b8caedd665455";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oSZ0+Cphy1+h6qn8IVKiv91+IhqUUOFnr+Ya+G+wPH0=";
    };
    date = "2023-03-21";
  };
  paper-store = {
    pname = "paper-store";
    version = "638a495e9b56262b981c7b19e82967495bdd1278";
    src = fetchgit {
      url = "https://github.com/nurupo/paper-store";
      rev = "638a495e9b56262b981c7b19e82967495bdd1278";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-aPxao4BZ15m6pEWPYhftbN/6Witu2GSydPforjt2sro=";
    };
    date = "2019-07-05";
  };
  pass-secret-service = {
    pname = "pass-secret-service";
    version = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
    src = fetchgit {
      url = "https://github.com/mdellweg/pass_secret_service.git";
      rev = "fadc09be718ae1e507eeb8719f3a2ea23edb6d7a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lrNU5bkG4/fMu5rDywfiI8vNHyBsMf/fiWIeEHug03c=";
    };
    date = "2022-07-18";
  };
  pbkdf2-sha512 = {
    pname = "pbkdf2-sha512";
    version = "c09a340472445317bdc3a48b91866b35b7986f03";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/NixOS/nixpkgs/master/nixos/modules/system/boot/pbkdf2-sha512.c";
      sha256 = "sha256-OelyIsDDto6Ir22YY/UM+r9EBx6K8TNdjM3efzUJxE8=";
    };
    date = "2023-05-01";
  };
  promnesia = {
    pname = "promnesia";
    version = "1f60af17761570b8a6787ebf0753ecfa750cad1b";
    src = fetchFromGitHub ({
      owner = "karlicoss";
      repo = "promnesia";
      rev = "1f60af17761570b8a6787ebf0753ecfa750cad1b";
      fetchSubmodules = false;
      sha256 = "sha256-iaMoNEz3bNNEH+K2vXu21T+JLQVGC7iq3PBjm4Vv+24=";
    });
    date = "2023-04-17";
  };
  quicklisp = {
    pname = "quicklisp";
    version = "latest";
    src = fetchurl {
      url = "https://beta.quicklisp.org/quicklisp.lisp";
      sha256 = "sha256-SnpcKuvgcWQXBHhUJnOX4kpE0MzglhJ0EenOnM/rLBc=";
    };
  };
  rage = {
    pname = "rage";
    version = "f84af2c069514ed61392597349d945680c51b074";
    src = fetchgit {
      url = "https://github.com/str4d/rage";
      rev = "f84af2c069514ed61392597349d945680c51b074";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-WryysUnHWC58fh+5yPOQO0DNnT1Vt09c+pZCZshrLLY=";
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2023-03-25";
  };
  rainbowsh = {
    pname = "rainbowsh";
    version = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
    src = fetchFromGitHub ({
      owner = "xr09";
      repo = "rainbow.sh";
      rev = "1bcf6e44a0d9694da4d3fa637644e5da5a7250ca";
      fetchSubmodules = false;
      sha256 = "sha256-F+Nabc/Fe5ET6lSkdll5YH/mEpKp3OlpaGk+u0rQpPQ=";
    });
    date = "2022-08-24";
  };
  remmina = {
    pname = "remmina";
    version = "v1.4.30";
    src = fetchgit {
      url = "https://gitlab.com/Remmina/Remmina";
      rev = "v1.4.30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-gZxUvVxd72cegObEOvkLoiDdcJ1XO455RqSocBUQ4RA=";
    };
  };
  rtl88x2bu = {
    pname = "rtl88x2bu";
    version = "281229078fd32c06ecf80c701ad5dd54a42d2f6a";
    src = fetchFromGitHub ({
      owner = "RinCat";
      repo = "RTL88x2BU-Linux-Driver";
      rev = "281229078fd32c06ecf80c701ad5dd54a42d2f6a";
      fetchSubmodules = false;
      sha256 = "sha256-ey/3wKZXeo4QE+IZ8xm4k6NYmGiku7m1QK3fPo30Ad8=";
    });
    date = "2023-03-14";
  };
  rubygems-huginn = {
    pname = "rubygems-huginn";
    version = "68b759a3f0874507d1871cf5c4700950579818d9";
    src = fetchFromGitHub ({
      owner = "huginn";
      repo = "huginn";
      rev = "68b759a3f0874507d1871cf5c4700950579818d9";
      fetchSubmodules = false;
      sha256 = "sha256-VcsvrJeUVUgr6yo+x/+HvdwPqCKaqZLImJIE9BF2IxE=";
    });
  };
  rubygems-nodejs-16-10-0 = {
    pname = "rubygems-nodejs-16-10-0";
    version = "v16.10.0";
    src = fetchFromGitHub ({
      owner = "nodejs";
      repo = "node";
      rev = "v16.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-YHhjHHJdRcKwok+EjIOHvtnr1OtZ44Ua1sdhnbV4OgI=";
    });
  };
  rubygems-solargraph = {
    pname = "rubygems-solargraph";
    version = "v0.44.2";
    src = fetchFromGitHub ({
      owner = "castwide";
      repo = "solargraph";
      rev = "v0.44.2";
      fetchSubmodules = false;
      sha256 = "sha256-TTUXO4E4U7abctoe9ys6SUete77CfzGq4YJOegWgNkw=";
    });
  };
  shellspec = {
    pname = "shellspec";
    version = "f800240b606ed8d60f27ca687400836c0083e76a";
    src = fetchFromGitHub ({
      owner = "shellspec";
      repo = "shellspec";
      rev = "f800240b606ed8d60f27ca687400836c0083e76a";
      fetchSubmodules = false;
      sha256 = "sha256-PyZBc7bmycV02nTpoDaA40m4DA1IuDmb/eCd3+RAp0o=";
    });
    date = "2022-05-04";
  };
  shflags = {
    pname = "shflags";
    version = "7d0daf1b3b3163c34e0108cdb439e2cd2f148152";
    src = fetchFromGitHub ({
      owner = "kward";
      repo = "shflags";
      rev = "7d0daf1b3b3163c34e0108cdb439e2cd2f148152";
      fetchSubmodules = false;
      sha256 = "sha256-t+6QCtpntU+2rjUlvCpGgsjU8ibWDHUP3MRGeAaRVbo=";
    });
    date = "2020-04-13";
  };
  spaceship-prompt = {
    pname = "spaceship-prompt";
    version = "e46f334c548734c8320a534afa8b84ae10db3e1f";
    src = fetchFromGitHub ({
      owner = "spaceship-prompt";
      repo = "spaceship-prompt";
      rev = "e46f334c548734c8320a534afa8b84ae10db3e1f";
      fetchSubmodules = false;
      sha256 = "sha256-Pbaxfpd9TC/9Gj6XXOXOcPTppRP6DKIjRkPHIPtLby0=";
    });
    date = "2023-04-21";
  };
  stumpwm = {
    pname = "stumpwm";
    version = "189a730f73266999d5b8f992faf939c11d7815ad";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "189a730f73266999d5b8f992faf939c11d7815ad";
      fetchSubmodules = false;
      sha256 = "sha256-jPxMo3QfqfSYTkKYnCf6CQhkSJrX90p70amSXynBxnE=";
    });
  };
  stumpwm-contrib = {
    pname = "stumpwm-contrib";
    version = "36daccd715e1cc6c1badab7cd87e34a8514f3b6b";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm-contrib";
      rev = "36daccd715e1cc6c1badab7cd87e34a8514f3b6b";
      fetchSubmodules = false;
      sha256 = "sha256-oW01W3ICwFdnDtO6y4aWXDIthw9iWU+lntNGcS80TXU=";
    });
    date = "2023-04-04";
  };
  stumpwm-git = {
    pname = "stumpwm-git";
    version = "9072f22e1b0fa6a9ce0e7658713fb61a9ddb1469";
    src = fetchFromGitHub ({
      owner = "stumpwm";
      repo = "stumpwm";
      rev = "9072f22e1b0fa6a9ce0e7658713fb61a9ddb1469";
      fetchSubmodules = false;
      sha256 = "sha256-GjTFUQ+qr6zXCxhSi8PqsWuBCKkb/RRfDkhzoBo9lBA=";
    });
    asd = "stumpwm";
    system = "stumpwm";
    date = "2023-04-29";
  };
  trezor-agent = {
    pname = "trezor-agent";
    version = "v0.14.5";
    src = fetchFromGitHub ({
      owner = "romanz";
      repo = "trezor-agent";
      rev = "v0.14.5";
      fetchSubmodules = false;
      sha256 = "sha256-RISAy0efdatr9u4CWNRGnlffkC8ksw1NyRpJWKwqz+s=";
    });
  };
  trezor-agent-subkeys = {
    pname = "trezor-agent-subkeys";
    version = "61dee859d49795bba0030b108dfc36963f4143cf";
    src = fetchgit {
      url = "https://github.com/jrruethe/trezor-agent";
      rev = "61dee859d49795bba0030b108dfc36963f4143cf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-llOdxTCKNhmiXG0dsa8cGpyhwUI+u9fEBPG0X88OTHQ=";
    };
    date = "2021-09-29";
  };
  trezor-gpg-pinentry-tk = {
    pname = "trezor-gpg-pinentry-tk";
    version = "0.0.10";
    src = fetchurl {
      url = "https://pypi.io/packages/source/t/trezor-gpg-pinentry-tk/trezor-gpg-pinentry-tk-0.0.10.tar.gz";
      sha256 = "sha256-h/NJKbKBP5Sbq0BYJes1h2ka2/k2gSUr564qOQZeAc4=";
    };
  };
  uhk-agent = {
    pname = "uhk-agent";
    version = "2.1.2";
    src = fetchurl {
      url = "https://github.com/UltimateHackingKeyboard/agent/releases/download/v2.1.2/UHK.Agent-2.1.2-linux-x86_64.AppImage";
      sha256 = "sha256-G/UT1ec7rWl8xONZnT+dpHAFOQh6/s0Vq7MTqAcmJSA=";
    };
  };
  vgo2nix = {
    pname = "vgo2nix";
    version = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
    src = fetchgit {
      url = "https://github.com/nix-community/vgo2nix";
      rev = "7641c5f139f7ebe33dd76e24f2c15a7c592c9ddd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6anZFfJe1Dw5LvwwR6e0EGtOrjwAQTHEdarbcMnTDEs=";
    };
    date = "2022-08-24";
  };
  xxhash2mac = {
    pname = "xxhash2mac";
    version = "f1013aba4892edd9b2467db764de20fa2b98c251";
    src = fetchgit {
      url = "https://github.com/njkli/xxhash2mac";
      rev = "f1013aba4892edd9b2467db764de20fa2b98c251";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-lU7CbcP48POPKD8Pibn4qxFCIGkiAbY/fC6irXAO4TU=";
    };
    date = "2022-03-22";
  };
  zero-ui = {
    pname = "zero-ui";
    version = "8785b94392e5de87b21fa93c81752ef67acc10f1";
    src = fetchgit {
      url = "https://github.com/dec0dOS/zero-ui";
      rev = "8785b94392e5de87b21fa93c81752ef67acc10f1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Db/z3pEk6eI9J0/NRh8XFFF3s6nSUTTYZLw28qE9PFE=";
    };
    date = "2022-12-30";
  };
  zeronsd = {
    pname = "zeronsd";
    version = "6105c6d565ae4d6c371f631e688b28ff9066077a";
    src = fetchFromGitHub ({
      owner = "voobscout";
      repo = "zeronsd";
      rev = "6105c6d565ae4d6c371f631e688b28ff9066077a";
      fetchSubmodules = false;
      sha256 = "sha256-CYMaZ8mL4S+kDpS5baEc3AzyfctIzZgyL87Ps1ekclk=";
    });
    cargoLock."Cargo.lock" = {
      lockFile = ./zeronsd-6105c6d565ae4d6c371f631e688b28ff9066077a/Cargo.lock;
      outputHashes = {
        
      };
    };
    cargoSha256 = "0000000000000000000000000000000000000000000000000000";
    date = "2022-10-30";
  };
  zsh-plugin_aw-watcher-shell = {
    pname = "zsh-plugin_aw-watcher-shell";
    version = "9dfe5199b10f00454c95dea9a33d9873e9bf9786";
    src = fetchgit {
      url = "https://github.com/nickbradley/aw-watcher-shell";
      rev = "9dfe5199b10f00454c95dea9a33d9873e9bf9786";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qPVAekgDrYoej4ycnJb+9Sz04oHfajC3MOgKxhyv7VE=";
    };
    date = "2019-07-19";
  };
  zsh-plugin_clipboard = {
    pname = "zsh-plugin_clipboard";
    version = "7fbd15150fe0fc84a34b6aa9e31c5589de3c9ffc";
    src = fetchgit {
      url = "https://github.com/zpm-zsh/clipboard";
      rev = "7fbd15150fe0fc84a34b6aa9e31c5589de3c9ffc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BaYYzl6JArfPWASJtzk44scGejwgyT5+W94ugVDCV3I=";
    };
    date = "2022-06-24";
  };
  zsh-plugin_k = {
    pname = "zsh-plugin_k";
    version = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
    src = fetchgit {
      url = "https://github.com/supercrabtree/k";
      rev = "e2bfbaf3b8ca92d6ffc4280211805ce4b8a8c19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-32rJjBzqS2e6w/L78KMNwQRg4E3sqqdAmb87XEhqbRQ=";
    };
    date = "2018-09-09";
  };
  zsh-plugin_oh-my-zsh = {
    pname = "zsh-plugin_oh-my-zsh";
    version = "2e7a247cab663fbc0aafdefa15bf10eb4dd64563";
    src = fetchgit {
      url = "https://github.com/robbyrussell/oh-my-zsh";
      rev = "2e7a247cab663fbc0aafdefa15bf10eb4dd64563";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-iAt93CsVuiptkyb0iMiNmXflKubAg9IUg3bhOyXMi1Y=";
    };
    date = "2023-04-28";
  };
  zsh-plugin_tipz = {
    pname = "zsh-plugin_tipz";
    version = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
    src = fetchgit {
      url = "https://github.com/molovo/tipz";
      rev = "594eab4642cc6dcfe063ecd51d76478bd84e2878";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oFZJwHYDfK4f53lhcZg6PCw2AgHxFC0CRiqiinKZz8k=";
    };
    date = "2018-05-03";
  };
  zsh-plugin_zsh-256color = {
    pname = "zsh-plugin_zsh-256color";
    version = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
    src = fetchgit {
      url = "https://github.com/chrissicool/zsh-256color";
      rev = "559fee48bb74b75cec8b9887f8f3e046f01d5d8f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-P/pbpDJmsMSZkNi5GjVTDy7R+OxaIVZhb/bEnYQlaLo=";
    };
    date = "2022-09-13";
  };
  zsh-plugin_zsh-autoenv = {
    pname = "zsh-plugin_zsh-autoenv";
    version = "e9809c1bd28496e025ca05576f574e08e93e12e8";
    src = fetchgit {
      url = "https://github.com/Tarrasch/zsh-autoenv";
      rev = "e9809c1bd28496e025ca05576f574e08e93e12e8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-SxDRldr9eqRtPQ3IWFKX0Q+vEG8Ry34PNRZ/I16aju0=";
    };
    date = "2018-09-14";
  };
  zsh-plugin_zsh-autopair = {
    pname = "zsh-plugin_zsh-autopair";
    version = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
    src = fetchgit {
      url = "https://github.com/hlissner/zsh-autopair";
      rev = "396c38a7468458ba29011f2ad4112e4fd35f78e6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PXHxPxFeoYXYMOC29YQKDdMnqTO0toyA7eJTSCV6PGE=";
    };
    date = "2022-10-03";
  };
  zsh-plugin_zsh-completions = {
    pname = "zsh-plugin_zsh-completions";
    version = "64ec7994dc1ecf7aa36d35574a45a203fdbbb6ad";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-completions";
      rev = "64ec7994dc1ecf7aa36d35574a45a203fdbbb6ad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3VHYrMI8MHiNfKLfZ+Rc5B4t0ywIRqlovasQToDGrz0=";
    };
    date = "2023-04-27";
  };
  zsh-plugin_zsh-history-substring-search = {
    pname = "zsh-plugin_zsh-history-substring-search";
    version = "400e58a87f72ecec14f783fbd29bc6be4ff1641c";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-history-substring-search";
      rev = "400e58a87f72ecec14f783fbd29bc6be4ff1641c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-GSEvgvgWi1rrsgikTzDXokHTROoyPRlU0FVpAoEmXG4=";
    };
    date = "2023-01-03";
  };
  zsh-plugin_zsh-syntax-highlighting = {
    pname = "zsh-plugin_zsh-syntax-highlighting";
    version = "754cefe0181a7acd42fdcb357a67d0217291ac47";
    src = fetchgit {
      url = "https://github.com/zsh-users/zsh-syntax-highlighting";
      rev = "754cefe0181a7acd42fdcb357a67d0217291ac47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pylOs3mGdpR/5+WjqKbkzb7t1d/o5b+HgRWZMN/Rw2c=";
    };
    date = "2023-02-05";
  };
  ztncui = {
    pname = "ztncui";
    version = "42248c13593e90f62238ee79ea5708a54eacf753";
    src = fetchgit {
      url = "https://github.com/key-networks/ztncui";
      rev = "42248c13593e90f62238ee79ea5708a54eacf753";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-8LBHVPBxx8pq4pUAOLxJMbnsxP1ZOHMAkbxNGWoQSFw=";
    };
    date = "2023-03-11";
  };
}
