# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  activitywatch = {
    pname = "activitywatch";
    version = "0.5.0";
    src = fetchurl {
      url = "https://activitywatch.gallery.vsassets.io/_apis/public/gallery/publisher/activitywatch/extension/aw-watcher-vscode/0.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "aw-watcher-vscode-0.5.0.zip";
      sha256 = "sha256-OrdIhgNXpEbLXYVJAx/jpt2c6Qa5jf8FNxqrbu5FfFs=";
    };
    name = "aw-watcher-vscode";
    publisher = "activitywatch";
  };
  ballerina = {
    pname = "ballerina";
    version = "4.5.23081103";
    src = fetchurl {
      url = "https://WSO2.gallery.vsassets.io/_apis/public/gallery/publisher/WSO2/extension/ballerina/4.5.23081103/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ballerina-4.5.23081103.zip";
      sha256 = "sha256-bipQKKCgwbepiBNU7xSWAzvZZ96yQuJqK6H5JdeoIXM=";
    };
    name = "ballerina";
    publisher = "WSO2";
  };
  codium = {
    pname = "codium";
    version = "0.7.17";
    src = fetchurl {
      url = "https://Codium.gallery.vsassets.io/_apis/public/gallery/publisher/Codium/extension/codium/0.7.17/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "codium-0.7.17.zip";
      sha256 = "sha256-Tyx5M1WCveXeyGCaSl1UicLYLqFC7ZxIvG6mWtyk3TM=";
    };
    name = "codium";
    publisher = "Codium";
  };
  copilot = {
    pname = "copilot";
    version = "1.136.550";
    src = fetchurl {
      url = "https://GitHub.gallery.vsassets.io/_apis/public/gallery/publisher/GitHub/extension/copilot/1.136.550/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "copilot-1.136.550.zip";
      sha256 = "sha256-bjOm4t9Rc0B8UBcYQZw4PlgBL5kQ01YgBDAKPBQ1jhs=";
    };
    name = "copilot";
    publisher = "GitHub";
  };
  crystal-lang = {
    pname = "crystal-lang";
    version = "0.8.4";
    src = fetchurl {
      url = "https://crystal-lang-tools.gallery.vsassets.io/_apis/public/gallery/publisher/crystal-lang-tools/extension/crystal-lang/0.8.4/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-lang-0.8.4.zip";
      sha256 = "sha256-hU6g4CqcCxXlhqSKL36vgzX2EJ7fIdbIuPCHbpRW/zE=";
    };
    name = "crystal-lang";
    publisher = "crystal-lang-tools";
  };
  crystal-spec-vscode = {
    pname = "crystal-spec-vscode";
    version = "0.1.0";
    src = fetchurl {
      url = "https://matthewmcgarvey.gallery.vsassets.io/_apis/public/gallery/publisher/matthewmcgarvey/extension/crystal-spec-vscode/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "crystal-spec-vscode-0.1.0.zip";
      sha256 = "sha256-3plr6exbkkaCSEcw766MFFI30NeQp+WNi1aAD4SpTT0=";
    };
    name = "crystal-spec-vscode";
    publisher = "matthewmcgarvey";
  };
  cucumberautocomplete = {
    pname = "cucumberautocomplete";
    version = "2.15.2";
    src = fetchurl {
      url = "https://alexkrechik.gallery.vsassets.io/_apis/public/gallery/publisher/alexkrechik/extension/cucumberautocomplete/2.15.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "cucumberautocomplete-2.15.2.zip";
      sha256 = "sha256-MdBJ71fIkIVOhLCoF/6/CATmUvutiTJPrIoVeb/eXc0=";
    };
    name = "cucumberautocomplete";
    publisher = "alexkrechik";
  };
  emacs-mcx = {
    pname = "emacs-mcx";
    version = "0.54.1";
    src = fetchurl {
      url = "https://tuttieee.gallery.vsassets.io/_apis/public/gallery/publisher/tuttieee/extension/emacs-mcx/0.54.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "emacs-mcx-0.54.1.zip";
      sha256 = "sha256-DcOd8e6/8+YJHWBeUDycAjYSCruISIl9ODVFtR1p2UA=";
    };
    name = "emacs-mcx";
    publisher = "tuttieee";
  };
  gherkintablealign = {
    pname = "gherkintablealign";
    version = "1.0.2";
    src = fetchurl {
      url = "https://AlanCole.gallery.vsassets.io/_apis/public/gallery/publisher/AlanCole/extension/gherkintablealign/1.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "gherkintablealign-1.0.2.zip";
      sha256 = "sha256-AhCm/GyleEOW9NlzE9uSJKIjM8RKQBjSM+RS1j3jiRM=";
    };
    name = "gherkintablealign";
    publisher = "AlanCole";
  };
  haml = {
    pname = "haml";
    version = "1.0.1";
    src = fetchurl {
      url = "https://vayan.gallery.vsassets.io/_apis/public/gallery/publisher/vayan/extension/haml/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "haml-1.0.1.zip";
      sha256 = "sha256-KTsKUfo7bfwqVMSAjRYuPuk+K5Qk+jBlHBlHWTunCdI=";
    };
    name = "haml";
    publisher = "vayan";
  };
  indent-rainbow = {
    pname = "indent-rainbow";
    version = "8.3.1";
    src = fetchurl {
      url = "https://oderwat.gallery.vsassets.io/_apis/public/gallery/publisher/oderwat/extension/indent-rainbow/8.3.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "indent-rainbow-8.3.1.zip";
      sha256 = "sha256-dOicya0B2sriTcDSdCyhtp0Mcx5b6TUaFKVb0YU3jUc=";
    };
    name = "indent-rainbow";
    publisher = "oderwat";
  };
  julia-color-themes = {
    pname = "julia-color-themes";
    version = "0.1.1";
    src = fetchurl {
      url = "https://cameronbieganek.gallery.vsassets.io/_apis/public/gallery/publisher/cameronbieganek/extension/julia-color-themes/0.1.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "julia-color-themes-0.1.1.zip";
      sha256 = "sha256-22TA7RpC0W3G8uA4EIqeuB4gqDF9cr1gNS+u7qQ3IaA=";
    };
    name = "julia-color-themes";
    publisher = "cameronbieganek";
  };
  language-julia = {
    pname = "language-julia";
    version = "1.60.2";
    src = fetchurl {
      url = "https://julialang.gallery.vsassets.io/_apis/public/gallery/publisher/julialang/extension/language-julia/1.60.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "language-julia-1.60.2.zip";
      sha256 = "sha256-aHvW/TlbhFCeUQeclbScFe2l+EUBr4/dkJ2TVII2UcU=";
    };
    name = "language-julia";
    publisher = "julialang";
  };
  markdown-preview-enhanced = {
    pname = "markdown-preview-enhanced";
    version = "0.8.10";
    src = fetchurl {
      url = "https://shd101wyy.gallery.vsassets.io/_apis/public/gallery/publisher/shd101wyy/extension/markdown-preview-enhanced/0.8.10/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "markdown-preview-enhanced-0.8.10.zip";
      sha256 = "sha256-BjTV2uH9QqCS1VJ94XXgzNMJb4FB4Ee+t/5uAQfJCuM=";
    };
    name = "markdown-preview-enhanced";
    publisher = "shd101wyy";
  };
  multi-cursor-case-preserve = {
    pname = "multi-cursor-case-preserve";
    version = "1.0.5";
    src = fetchurl {
      url = "https://Cardinal90.gallery.vsassets.io/_apis/public/gallery/publisher/Cardinal90/extension/multi-cursor-case-preserve/1.0.5/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "multi-cursor-case-preserve-1.0.5.zip";
      sha256 = "sha256-eJafjYDydD8DW83VLH9MPFeDENXBx3el7XvjZqu88Jw=";
    };
    name = "multi-cursor-case-preserve";
    publisher = "Cardinal90";
  };
  nickel-syntax = {
    pname = "nickel-syntax";
    version = "0.0.2";
    src = fetchurl {
      url = "https://kubukoz.gallery.vsassets.io/_apis/public/gallery/publisher/kubukoz/extension/nickel-syntax/0.0.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nickel-syntax-0.0.2.zip";
      sha256 = "sha256-ffPZd717Y2OF4d9MWE6zKwcsGWS90ZJvhWkqP831tVM=";
    };
    name = "nickel-syntax";
    publisher = "kubukoz";
  };
  nix-extension-pack = {
    pname = "nix-extension-pack";
    version = "3.0.0";
    src = fetchurl {
      url = "https://pinage404.gallery.vsassets.io/_apis/public/gallery/publisher/pinage404/extension/nix-extension-pack/3.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-extension-pack-3.0.0.zip";
      sha256 = "sha256-cWXd6AlyxBroZF+cXZzzWZbYPDuOqwCZIK67cEP5sNk=";
    };
    name = "nix-extension-pack";
    publisher = "pinage404";
  };
  nix-ide = {
    pname = "nix-ide";
    version = "0.2.2";
    src = fetchurl {
      url = "https://jnoortheen.gallery.vsassets.io/_apis/public/gallery/publisher/jnoortheen/extension/nix-ide/0.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-ide-0.2.2.zip";
      sha256 = "sha256-jwOM+6LnHyCkvhOTVSTUZvgx77jAg6hFCCpBqY8AxIg=";
    };
    name = "nix-ide";
    publisher = "jnoortheen";
  };
  pdf = {
    pname = "pdf";
    version = "1.2.2";
    src = fetchurl {
      url = "https://tomoki1207.gallery.vsassets.io/_apis/public/gallery/publisher/tomoki1207/extension/pdf/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "pdf-1.2.2.zip";
      sha256 = "sha256-i3Rlizbw4RtPkiEsodRJEB3AUzoqI95ohyqZ0ksROps=";
    };
    name = "pdf";
    publisher = "tomoki1207";
  };
  rails-snippets = {
    pname = "rails-snippets";
    version = "1.0.8";
    src = fetchurl {
      url = "https://hridoy.gallery.vsassets.io/_apis/public/gallery/publisher/hridoy/extension/rails-snippets/1.0.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "rails-snippets-1.0.8.zip";
      sha256 = "sha256-OSh/BhBxs4Vx5s8tTRlEIlk9sXRvpjLqZ6BqjGLgemA=";
    };
    name = "rails-snippets";
    publisher = "hridoy";
  };
  readable-indent = {
    pname = "readable-indent";
    version = "1.2.2";
    src = fetchurl {
      url = "https://cnojima.gallery.vsassets.io/_apis/public/gallery/publisher/cnojima/extension/readable-indent/1.2.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "readable-indent-1.2.2.zip";
      sha256 = "sha256-iTgbxasaNTIBlLLUPs00Y9x099zfXc6ES6drTc8CE78=";
    };
    name = "readable-indent";
    publisher = "cnojima";
  };
  remote-ssh-edit = {
    pname = "remote-ssh-edit";
    version = "0.86.0";
    src = fetchurl {
      url = "https://ms-vscode-remote.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode-remote/extension/remote-ssh-edit/0.86.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "remote-ssh-edit-0.86.0.zip";
      sha256 = "sha256-JsbaoIekUo2nKCu+fNbGlh5d1Tt/QJGUuXUGP04TsDI=";
    };
    name = "remote-ssh-edit";
    publisher = "ms-vscode-remote";
  };
  ruby = {
    pname = "ruby";
    version = "0.1.0";
    src = fetchurl {
      url = "https://groksrc.gallery.vsassets.io/_apis/public/gallery/publisher/groksrc/extension/ruby/0.1.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-0.1.0.zip";
      sha256 = "sha256-JrkzYKjRf1bExSrZOQxek9TS+K14jcJYxjNCEqqHcdk=";
    };
    name = "ruby";
    publisher = "groksrc";
  };
  ruby-linter = {
    pname = "ruby-linter";
    version = "1.0.0";
    src = fetchurl {
      url = "https://hoovercj.gallery.vsassets.io/_apis/public/gallery/publisher/hoovercj/extension/ruby-linter/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-linter-1.0.0.zip";
      sha256 = "sha256-DqykFLOQgv10xw/Q2ZtyW1ATOhI61+IY/6lrc9/ln3w=";
    };
    name = "ruby-linter";
    publisher = "hoovercj";
  };
  ruby-lsp = {
    pname = "ruby-lsp";
    version = "0.5.0";
    src = fetchurl {
      url = "https://Shopify.gallery.vsassets.io/_apis/public/gallery/publisher/Shopify/extension/ruby-lsp/0.5.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-lsp-0.5.0.zip";
      sha256 = "sha256-Wx3s5m/QZuCmZK/iRRPGWOe8n+g5GGKWrvhYewvq3lQ=";
    };
    name = "ruby-lsp";
    publisher = "Shopify";
  };
  ruby-rubocop = {
    pname = "ruby-rubocop";
    version = "0.8.6";
    src = fetchurl {
      url = "https://misogi.gallery.vsassets.io/_apis/public/gallery/publisher/misogi/extension/ruby-rubocop/0.8.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-rubocop-0.8.6.zip";
      sha256 = "sha256-6hgJzOerGCCXcpADnISa7ewQnRWLAn6k6K4kLJR09UI=";
    };
    name = "ruby-rubocop";
    publisher = "misogi";
  };
  ruby-symbols = {
    pname = "ruby-symbols";
    version = "0.1.8";
    src = fetchurl {
      url = "https://miguel-savignano.gallery.vsassets.io/_apis/public/gallery/publisher/miguel-savignano/extension/ruby-symbols/0.1.8/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "ruby-symbols-0.1.8.zip";
      sha256 = "sha256-3IsqJ46IG0O2g7hKBt0OgQwruaGu9TuA3XpjAjAk550=";
    };
    name = "ruby-symbols";
    publisher = "miguel-savignano";
  };
  simple-ruby-erb = {
    pname = "simple-ruby-erb";
    version = "0.2.1";
    src = fetchurl {
      url = "https://vortizhe.gallery.vsassets.io/_apis/public/gallery/publisher/vortizhe/extension/simple-ruby-erb/0.2.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "simple-ruby-erb-0.2.1.zip";
      sha256 = "sha256-JZov46QWUHIewu4FZtlQL/wRV6rHpu6Kd9yuWdCL77w=";
    };
    name = "simple-ruby-erb";
    publisher = "vortizhe";
  };
  solargraph = {
    pname = "solargraph";
    version = "0.24.0";
    src = fetchurl {
      url = "https://castwide.gallery.vsassets.io/_apis/public/gallery/publisher/castwide/extension/solargraph/0.24.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "solargraph-0.24.0.zip";
      sha256 = "sha256-7mMzN+OdJ5R9CVaBJMzW218wMG5ETvNrUTST9/kjjV0=";
    };
    name = "solargraph";
    publisher = "castwide";
  };
  tabnine-vscode = {
    pname = "tabnine-vscode";
    version = "3.31.0";
    src = fetchurl {
      url = "https://TabNine.gallery.vsassets.io/_apis/public/gallery/publisher/TabNine/extension/tabnine-vscode/3.31.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tabnine-vscode-3.31.0.zip";
      sha256 = "sha256-o7Nxm3fObtLC40blCe1mu9g88Be4jrDgYE+PCo1f5P0=";
    };
    name = "tabnine-vscode";
    publisher = "TabNine";
  };
  tokyo-night = {
    pname = "tokyo-night";
    version = "1.0.6";
    src = fetchurl {
      url = "https://enkia.gallery.vsassets.io/_apis/public/gallery/publisher/enkia/extension/tokyo-night/1.0.6/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "tokyo-night-1.0.6.zip";
      sha256 = "sha256-VWdUAU6SC7/dNDIOJmSGuIeffbwmcfeGhuSDmUE7Dig=";
    };
    name = "tokyo-night";
    publisher = "enkia";
  };
  vscode-direnv = {
    pname = "vscode-direnv";
    version = "1.0.0";
    src = fetchurl {
      url = "https://cab404.gallery.vsassets.io/_apis/public/gallery/publisher/cab404/extension/vscode-direnv/1.0.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-direnv-1.0.0.zip";
      sha256 = "sha256-+nLH+T9v6TQCqKZw6HPN/ZevQ65FVm2SAo2V9RecM3Y=";
    };
    name = "vscode-direnv";
    publisher = "cab404";
  };
  vscode-docker = {
    pname = "vscode-docker";
    version = "1.28.0";
    src = fetchurl {
      url = "https://ms-azuretools.gallery.vsassets.io/_apis/public/gallery/publisher/ms-azuretools/extension/vscode-docker/1.28.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-docker-1.28.0.zip";
      sha256 = "sha256-ACaVwRTN4lu97GDGzxyzX/O10p6fNT3FNLne/todrFo=";
    };
    name = "vscode-docker";
    publisher = "ms-azuretools";
  };
  vscode-emacs-friendly = {
    pname = "vscode-emacs-friendly";
    version = "0.9.0";
    src = fetchurl {
      url = "https://lfs.gallery.vsassets.io/_apis/public/gallery/publisher/lfs/extension/vscode-emacs-friendly/0.9.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-friendly-0.9.0.zip";
      sha256 = "sha256-YWu2a5hz0qGZvgR95DbzUw6PUvz17i1o4+eAUM/xjMg=";
    };
    name = "vscode-emacs-friendly";
    publisher = "lfs";
  };
  vscode-emacs-tab = {
    pname = "vscode-emacs-tab";
    version = "0.2.0";
    src = fetchurl {
      url = "https://garaemon.gallery.vsassets.io/_apis/public/gallery/publisher/garaemon/extension/vscode-emacs-tab/0.2.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-emacs-tab-0.2.0.zip";
      sha256 = "sha256-Ulwe5s/qieF7n6ymW6UdyRCUYN5LRG7pj6WyZyLNg9A=";
    };
    name = "vscode-emacs-tab";
    publisher = "garaemon";
  };
  vscode-markdownlint = {
    pname = "vscode-markdownlint";
    version = "0.52.0";
    src = fetchurl {
      url = "https://DavidAnson.gallery.vsassets.io/_apis/public/gallery/publisher/DavidAnson/extension/vscode-markdownlint/0.52.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "vscode-markdownlint-0.52.0.zip";
      sha256 = "sha256-Y8qkcNEvJ/yzT8PDeErRzKGxYBNKKfbNNsJVaFDeIV4=";
    };
    name = "vscode-markdownlint";
    publisher = "DavidAnson";
  };
  zeek = {
    pname = "zeek";
    version = "0.6.0";
    src = fetchurl {
      url = "https://aeppert.gallery.vsassets.io/_apis/public/gallery/publisher/aeppert/extension/bro/0.6.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "bro-0.6.0.zip";
      sha256 = "sha256-+wISGCtGq/l058dOaAKlD3pGknP2ksekS1Rgmax5QgU=";
    };
    name = "bro";
    publisher = "aeppert";
  };
}
